from __future__ import annotations

from datetime import date
from pathlib import Path

import pytest
from typer.testing import CliRunner

from smairt.cli import app
from smairt.index import scan_units, write_index
from smairt.project import Harness, create_project
from smairt.units import create_question, create_stage

runner = CliRunner()


def _project(tmp_path: Path) -> Path:
    root = tmp_path / "project"
    create_project(
        root,
        name="Index Test Project",
        researcher="Ada Lovelace",
        description="Exercises index generation.",
        harness=Harness.claude_code,
        created=date(2026, 1, 1),
        scaffold_version="0.0.0-test",
    )
    return root


def test_scan_units_is_empty_for_a_fresh_project(tmp_path: Path) -> None:
    root = _project(tmp_path)

    assert scan_units(root) == []


def test_scan_units_lists_every_unit_with_its_evidence(tmp_path: Path) -> None:
    root = _project(tmp_path)
    stage = create_stage(root, "Alignment", created=date(2026, 1, 5))
    (stage / "logs" / "run.log").write_text("log\n", encoding="utf-8")
    (stage / "figures" / "coverage.png").write_bytes(b"fake-png")
    create_question(root, "Batch effect check", created=date(2026, 1, 6))

    records = scan_units(root)

    assert [record.path for record in records] == [
        "experiments/01_alignment",
        "experiments/2026-01-06_batch-effect-check",
    ]
    alignment = records[0]
    assert alignment.kind == "stage"
    assert alignment.status == "active"
    assert alignment.title == "Alignment"
    assert alignment.logs == ("run.log",)
    assert alignment.figures == ("coverage.png",)


def test_write_index_regenerates_the_table(tmp_path: Path) -> None:
    root = _project(tmp_path)
    create_stage(root, "Alignment", created=date(2026, 1, 5))

    path = write_index(root)
    content = path.read_text()

    assert "experiments/01_alignment" in content
    assert "Generated by `smairt index`" in content

    # A second unit added later is picked up on regeneration (derived-first state).
    create_question(root, "Follow-up probe", created=date(2026, 1, 6))
    write_index(root)
    content = path.read_text()
    assert "experiments/2026-01-06_follow-up-probe" in content


def test_write_index_overwrites_previous_content_even_though_it_is_generated(
    tmp_path: Path,
) -> None:
    root = _project(tmp_path)
    index_path = root / "results" / "INDEX.md"
    index_path.write_text("stale content that should be replaced\n", encoding="utf-8")

    write_index(root)

    assert "stale content" not in index_path.read_text()


def test_scan_units_handles_a_reference_unit_with_no_logs_folder(tmp_path: Path) -> None:
    root = _project(tmp_path)
    (root / "data" / "old_analysis").mkdir(parents=True)
    create_question(root, "Old DE run", ref_paths=["data/old_analysis"], created=date(2026, 1, 6))

    records = scan_units(root)

    assert len(records) == 1
    assert records[0].logs == ()
    assert records[0].figures == ()

    # Regenerating the index must not crash for a unit with no logs/figures/.
    write_index(root)


def test_cli_index_command(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    root = _project(tmp_path)
    create_stage(root, "Alignment", created=date(2026, 1, 5))
    monkeypatch.chdir(root)

    result = runner.invoke(app, ["index"])

    assert result.exit_code == 0, result.output
    assert "experiments/01_alignment" in (root / "results" / "INDEX.md").read_text()


def test_cli_index_refuses_outside_a_project(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.chdir(tmp_path)

    result = runner.invoke(app, ["index"])

    assert result.exit_code != 0
    assert "not a SMAIRT project" in result.output
