"""``smairt check`` — the state contract (WP2).

Tier-2 enforcement (spec Part I, foundation 2): what tooling cannot generate at
creation time (tier 1), it verifies mechanically here. Derived-first (foundation
3): this module reads frontmatter, the filesystem, and Git; it never maintains a
database of its own, and it never writes anything — the one deliberate exception
elsewhere in the codebase, ``results/INDEX.md``, is regenerated by
:mod:`smairt.index`, not here.

Public entry point: :func:`run_checks`, returning a :class:`CheckReport`.

:func:`read_status` is the single reader of ``STATUS.md`` (frontmatter *and* its
``## Heading`` body sections) — reused by rule 5 below and by ``smairt status`` (WP3).

Finding IDs
-----------
Every rule below carries exactly one stable ID (the *rule* is the unit of
identity, not each way it can be violated — a rule's ``message`` text carries
the specifics). IDs are referenced by tests and, later, by WP4's hooks, so they
must not be renumbered once shipped.

Findings (severity error/warning; each instance affects the process exit code)::

    SMAIRT001  Frontmatter schema invalid: block missing/malformed, kind not
               recognized, status illegal for that kind, or a required field
               (per smairt.units) absent.                              [error]
    SMAIRT002  An evidence pointer (script:/log:/outputs:/paths:) does not
               resolve, or a CLOSED unit's script:/log: is empty.       [error]
    SMAIRT003  Receipt completeness: a unit with tool: set has an empty
               tool_version:, empty command:, or a log: that does not exist.
                                                                          [error]
    SMAIRT004  Raw-log immutability: a file under a unit's logs/ was modified
               in a later commit than the one that added it.            [error]
    SMAIRT005  STATUS drift: STATUS.md's updated: is older than a unit that
               has changed since.                                     [warning]
    SMAIRT006  Structure drift: a file loose directly under experiments/
               (outside any unit folder), or an unrecognized top-level
               project folder.                                        [warning]
    SMAIRT007  Closed-question completeness: status in {supported, refuted,
               inconclusive, dead-end} with an empty verdict:.          [error]
    SMAIRT008  A question's prompted_by: is set but does not resolve to a
               real unit (a folder with its own README.md) under
               experiments/.                                            [error]
    SMAIRT009  A question unit's hypothesis: is present but empty
               (reference units, case 3, are exempt).                   [error]
    SMAIRT010  A CLOSED question unit's '## Analysis plan' body section is
               missing or empty (reference units, case 3, are exempt).  [error]
    SMAIRT011  The project's own smairt.yaml parses but is missing, or has
               emptied out, a required identity field (name:/researcher:/
               description:).                                            [error]
    SMAIRT012  A folder directly under experiments/ has no README.md, so it
               is invisible to check/status/index.                     [warning]
    SMAIRT013  A question's prompted_by: chain loops back on itself (a
               cycle, only reachable by hand-editing frontmatter).        [error]

Advisory suggestions (a separate channel; never affect the exit code)::

    SMAIRT101  Git is unavailable, so raw-log immutability (rule SMAIRT004)
               could not be checked at all — one note, not per-file. Suppressed
               (DG-5) when smairt.yaml records the researcher's own choice not
               to use Git; still fires whenever that choice is absent or true.
    SMAIRT102  SLURM/sbatch content found in a unit but the project has no
               hpc/ folder yet.
    SMAIRT103  Three or more question units share a leading slug word: a
               grouping subfolder may be earned.
    SMAIRT104  STATUS.md mentions paper/manuscript/figure-legend work: a
               pointer to the (deferred) Paper overlay.
    SMAIRT105  A data/<x>/ subfolder exists with no README, or a README with
               no locations: entry recorded -- one note, not per-dataset.

Judgment calls a reviewer should know about
--------------------------------------------
* ``smairt unit new question`` pre-fills ``log:`` with the filename the probe
  is expected to write (``logs/<slug>.log``) before it has run. Rule SMAIRT002
  treats that as resolved for an OPEN/ACTIVE unit as long as the containing
  ``logs/`` folder exists — only a CLOSED unit is held to the exact file
  existing. This is what lets a freshly created, not-yet-run question pass
  check with zero findings (WP1's own acceptance criterion).
* Rule SMAIRT004 (log immutability) is skipped, in favor of the single
  SMAIRT101 advisory, whenever the project is not inside a Git work tree —
  this keeps `smairt check` usable before a researcher runs ``git init``.
* Rule SMAIRT005 (STATUS drift) compares calendar dates only (a file's mtime
  truncated to a date vs. STATUS.md's ``updated:`` date), not timestamps —
  matching the day-granularity the frontmatter schemas already use.
* Rule 8's growth suggestions each fire at most once per run (naming the
  first offending unit, not every one) — they are prompts to notice a
  pattern, not a per-file audit. SMAIRT105 (dataset locations) follows the
  same convention, naming the first data/<x>/ subfolder missing a recorded
  location rather than every one — a project can accumulate many datasets,
  and one nudge is enough to send a researcher to `smairt data list` to see
  the rest, rather than flooding `smairt check`'s output per dataset.
* Rule SMAIRT002's ``paths:`` field (case 3, spec Part II: reference units)
  resolves relative to the PROJECT ROOT, not the unit folder — it names
  pre-existing paths elsewhere in the tree. Every other pointer field
  (``script:``/``log:``/``outputs:``) stays unit-relative, as before.
* Rule SMAIRT002 (and rule 8's ``prompted_by:`` check, which mirrors it)
  never treats an ABSOLUTE pointer value as resolved, even when the absolute
  path genuinely exists on disk. ``pathlib`` joins an absolute right-hand
  side by discarding the left side entirely, so without this guard an
  absolute ``script:``/``log:``/``outputs:``/``paths:`` value would be
  checked against the whole filesystem instead of the project root/unit
  folder it's documented to resolve against — the one place in this module
  where "the pointer happens to exist" and "the pointer is valid" can
  silently diverge. See :func:`_pointer_resolves`.
* Rule SMAIRT006 (structure drift) also recognizes ``smairt.yaml``'s
  ``adoption.known_folders`` (written by ``smairt adopt``) as legitimate
  top-level folders, on top of the fixed scaffold set — an adopted project's
  pre-existing directories don't warn; anything new appearing after adoption
  still does.
* The one ``smairt.yaml`` degrade policy (DG-1) splits on reads versus
  writes, not on call sites. Unparseable YAML fails fast for every command at
  project-root resolution; a file that parses but is invalid is rule
  SMAIRT011. Below that, a *read* falls back silently to a documented safe
  default (:func:`smairt.connect.read_strict_hooks` -> non-strict,
  :func:`_adoption_known_folders` -> no known folders), because nothing the
  researcher asked for has gone missing. A *write* that cannot happen always
  warns (:func:`smairt.connect._record_harness`): the researcher asked for it,
  and silence would let a command report success while the change never
  landed.
* Rule SMAIRT008 (``prompted_by:`` resolves) treats a target as resolved only
  when ``experiments/<target>/README.md`` exists — the same "must actually be
  a unit, not just a folder" standard rule SMAIRT002 already holds reference
  units' ``paths:`` to. It only ever fires when ``prompted_by:`` is present;
  nothing requires the field, per spec ticket 01's answer.
* Rules SMAIRT009 (hypothesis) and SMAIRT010 (Analysis plan) both exempt
  reference units — detected the same way :func:`_check_evidence_pointers`
  distinguishes them, by ``"paths" in unit.fields`` — from firing at all. A
  reference unit describes work adopted after the fact; it was never framed
  as a testable claim, so demanding a retroactive hypothesis or plan for it
  would be absurd. Spec ticket 02 states this exemption explicitly for the
  Analysis plan rule; the hypothesis rule is new territory the ticket didn't
  directly address, but the same reasoning applies without change, so the
  same exemption is used for both.
* Rule SMAIRT009 skips a question whose ``hypothesis:`` key is absent from
  frontmatter entirely, as opposed to present-but-blank — rule SMAIRT001
  already reports a missing required field as its own finding, and firing
  both for the same defect would just be noise. This mirrors how rule
  SMAIRT002 skips a pointer field that isn't present at all (see
  :func:`_check_evidence_pointers`).
* Rule SMAIRT010 reuses :func:`_split_status_sections` against a question
  unit's own README body, not just ``STATUS.md`` — the function was already
  a generic ``## Heading`` splitter with nothing STATUS-specific in its
  implementation, so extending its one caller to two rather than writing a
  second parser was the whole point of the ticket's "reuse read_status's
  approach" instruction.
* **DG-1's degrade policy, decided once and applied everywhere:** a
  ``smairt.yaml`` that fails to PARSE (a genuine YAML syntax error) is caught
  as early as possible — :func:`smairt.project.find_project_root`, which
  every command already calls to resolve "which project am I in", raises
  :class:`smairt.project.ProjectConfigError` and every command turns that
  into a `smairt <command>: ...` failure before doing anything else. A
  ``smairt.yaml`` that PARSES but is empty, isn't a mapping, or is missing a
  required identity field is instead rule SMAIRT011 below — it can only be
  reached once the project root is already known-good, so it is a `check`
  finding like any other, not a second fail-fast path. Every OTHER reader of
  ``smairt.yaml`` in this codebase (this rule's own
  :func:`_adoption_known_folders`, and :mod:`smairt.connect`'s
  ``read_strict_hooks``/``_record_harness``) goes through the single shared
  :func:`smairt.project.read_project_config` and, on failure, silently falls
  back to its own safe default (no known folders / ``strict_hooks: False`` /
  the ``harnesses:`` list left untouched) — it does NOT print its own
  warning. This replaces the previous per-call-site inconsistency (
  ``_adoption_known_folders`` and ``read_strict_hooks`` degraded silently
  while ``_record_harness`` warned on the identical failure) with one rule:
  a broken ``smairt.yaml`` is always surfaced through exactly one of the two
  systematic channels above (fail-fast or SMAIRT011), never through an ad
  hoc per-function message that would just repeat the same news a third or
  fourth time. In the realistic case — a researcher breaks the file's YAML
  *syntax* by hand — fail-fast already stops every command, including
  ``smairt connect``, before ``read_strict_hooks`` or ``_record_harness``
  ever run, which is what actually fixes the walk's worst finding here (a
  broken file silently costing a researcher their ``strict_hooks: true``
  gate). The remaining "valid YAML, wrong shape" case is only reachable by a
  much stranger hand-edit (replacing the whole mapping with a bare list, for
  instance); it still gets caught, just the next time `smairt check` runs
  rather than instantly.
* **DG-1's required fields.** Rule SMAIRT011 requires exactly ``name:``,
  ``researcher:``, ``description:`` — the three fields
  ``_prompt_missing_identity`` (cli.py) actually asks a researcher for, and
  the only three a human being is likely to ever hand-edit. ``schema_version``/
  ``scaffold_version``/``created``/``harnesses``/``settings`` are smairt's own
  bookkeeping, already read defensively (``.get(...)`` with a fallback)
  everywhere they're consumed, and are not something a researcher edits by
  hand or would know how to "fix" if flagged — flagging them would turn this
  rule from "your project doesn't say who/what this is" into unhelpful
  pedantry about internal fields.
* **DG-1's message, one finding per broken file.** Rule SMAIRT011 emits at
  most ONE finding for a broken ``smairt.yaml`` (naming every missing/empty
  field it found, not just the first), rather than one finding per field —
  the hard requirement is that the message end by showing what a correct
  file looks like (:func:`smairt.project.example_smairt_yaml`), and pasting
  that same ~9-line block two or three times over for a file missing several
  fields would bury the useful part in repetition instead of helping.
* **DG-2 (rule SMAIRT012)** matches SMAIRT006's severity (warning, not
  error/suggestion) because it is the same class of problem — the project
  still "works", it just doesn't match the shape `smairt` can see — and the
  message points at ``smairt unit new`` as the one supported fix, the same
  as :mod:`smairt`'s ``AGENTS.md`` template already tells every researcher.
  Deliberately does not attempt to guess whether the folder is stage-shaped
  or question-shaped; that's a judgment call for the researcher, not this
  rule.
* **DG-3's SMAIRT006 sharpening**: when an unrecognized top-level folder
  itself contains a ``smairt.yaml``, :func:`_check_structure_drift` names
  that specifically ("is itself a SMAIRT project") instead of the generic
  "not part of the known scaffold" text — this is the same situation
  ``smairt new``'s own nesting warning (see :func:`smairt.project.
  find_enclosing_project`, called from ``cli.py``'s ``new`` command) already
  warns about at creation time; this is the backstop for finding it later
  (adopted from elsewhere, created before this check existed, or the warning
  was missed).
* **DG-4 (rule SMAIRT013, prompted_by cycles)**: :func:`_check_prompted_by_cycle`
  is a SEPARATE, from-scratch cycle walk over the same ``prompted_by:``
  edges rule SMAIRT008 already validates resolve — it deliberately does not
  reuse or touch :func:`smairt.index._ordered_for_index`'s own cycle guard,
  which the friction walk already verified (under a hard 15-second timeout)
  never hangs or crashes; this rule only ADDS a report of what that guard
  was silently working around. Only edges that already resolve (per
  :func:`_prompted_by_resolves`) participate — a dangling ``prompted_by:``
  is SMAIRT008's finding, not a cycle candidate, so the two rules never fire
  on the same root cause. Because each question has at most one
  ``prompted_by:`` target, the graph has out-degree <= 1 everywhere, which
  is what makes an O(n) three-color walk (unvisited/in-progress/done)
  sufficient — no recursion depth concerns, no need for a general-graph
  algorithm. A unit naming ITSELF as ``prompted_by:`` is treated as a
  degenerate, length-1 cycle, not silently ignored: it "resolves" by
  SMAIRT008's own rule (the unit's own README.md genuinely exists at that
  path), so SMAIRT008 never catches it, even though "prompted by itself" is
  exactly as impossible in real work as any longer loop. This differs from
  :func:`smairt.index._ordered_for_index`, which also refuses to nest a
  record under itself — but only to decide it shouldn't render as its own
  parent, a rendering choice this rule has no reason to copy.
* **DG-5 (SMAIRT101 suppression on a recorded git opt-out)**: a researcher who
  answers "no" to ``smairt new``'s Git prompt (or passes ``--no-git``) gets
  ``settings.git: false`` written into ``smairt.yaml``
  (:func:`smairt.project.render_identity`); :func:`_git_opt_out_recorded`
  reads it back defensively, the same shape as
  :func:`smairt.connect.read_strict_hooks`. SMAIRT101 exists to flag a
  project that has *no history to check* — usually because nobody ever ran
  ``git init``, an oversight worth a nudge. A deliberate, recorded no-git
  choice is a different fact: there will never be Git history to check,
  on purpose, so repeating the nudge every single ``smairt check`` forever
  would just be the tool arguing with a decision already made. This
  deliberately does NOT touch rule SMAIRT004 itself (log immutability):
  SMAIRT004 already only runs when :func:`smairt.project.is_git_work_tree`
  is true, so a no-Git project never reaches it either way — the opt-out
  only changes whether the ADVISORY about not being able to run it also
  fires, never a finding's severity or existence. Never promoted to a
  finding and never given its own rule id: it changes exactly one existing
  suggestion's firing condition, not the state contract itself.
"""

from __future__ import annotations

import subprocess
from dataclasses import asdict, dataclass
from datetime import date, datetime
from pathlib import Path
from typing import Any

from smairt import frontmatter
from smairt import project as project_module
from smairt import units as units_module
from smairt.units import UnitKind

ERROR = "error"
WARNING = "warning"

RULE_FRONTMATTER = "SMAIRT001"
RULE_EVIDENCE_POINTERS = "SMAIRT002"
RULE_RECEIPT_COMPLETENESS = "SMAIRT003"
RULE_LOG_IMMUTABILITY = "SMAIRT004"
RULE_STATUS_DRIFT = "SMAIRT005"
RULE_STRUCTURE_DRIFT = "SMAIRT006"
RULE_CLOSED_QUESTION = "SMAIRT007"
RULE_PROMPTED_BY = "SMAIRT008"
RULE_HYPOTHESIS_NONEMPTY = "SMAIRT009"
RULE_ANALYSIS_PLAN = "SMAIRT010"
RULE_PROJECT_CONFIG = "SMAIRT011"
RULE_MISSING_README = "SMAIRT012"
RULE_PROMPTED_BY_CYCLE = "SMAIRT013"

SUGGEST_GIT_UNAVAILABLE = "SMAIRT101"
SUGGEST_HPC = "SMAIRT102"
SUGGEST_GROUPING = "SMAIRT103"
SUGGEST_PAPER_OVERLAY = "SMAIRT104"
SUGGEST_DATASET_LOCATIONS = "SMAIRT105"

_POINTER_FIELDS = ("script", "log", "outputs", "paths")
_KNOWN_TOP_LEVEL_DIRS = frozenset(
    {"background", "data", "scripts", "experiments", "results", "hpc"}
)
_CLOSED_STAGE_STATUSES = frozenset({"frozen", "dead-end"})
_CLOSED_QUESTION_STATUSES = frozenset({"supported", "refuted", "inconclusive", "dead-end"})
_PAPER_WORDS = ("paper", "manuscript", "figure legend")


@dataclass(frozen=True)
class Finding:
    """One violation of the state contract. ``severity`` is ``error`` or ``warning``."""

    id: str
    severity: str
    path: str
    message: str


@dataclass(frozen=True)
class Suggestion:
    """One growth-channel note. Advisory only: never affects the exit code."""

    id: str
    path: str
    message: str


@dataclass(frozen=True)
class CheckReport:
    """The full result of :func:`run_checks`."""

    findings: tuple[Finding, ...]
    suggestions: tuple[Suggestion, ...]

    @property
    def exit_code(self) -> int:
        """1 if there are any errors/warnings, else 0 — what the CLI process exits with.

        Suggestions never affect this: they're advisory-only, so a project
        with suggestions but zero findings still exits 0 (success).
        """
        return 1 if self.findings else 0


@dataclass(frozen=True)
class StatusDocument:
    """The parsed contents of STATUS.md — the project's one hand-maintained ledger
    (Part I, foundation 3). This is the single reader for STATUS.md: :func:`run_checks`
    consults only ``updated`` (rule 5, STATUS drift); ``smairt status`` (WP3) reads the
    rest to print Focus/Next/Open questions. Keeping both behind :func:`read_status`
    means there is exactly one place that parses this file.
    """

    updated: date | None
    focus: str
    next_step: str
    open_questions: tuple[str, ...]
    decisions: tuple[str, ...]


def read_status(project_root: Path) -> StatusDocument | None:
    """Read and parse ``STATUS.md``, or ``None`` if it is absent or malformed."""
    status_path = project_root / "STATUS.md"
    if not status_path.is_file():
        return None
    try:
        fields, body = frontmatter.read(status_path)
    except frontmatter.FrontmatterError:
        return None
    sections = _split_status_sections(body)
    return StatusDocument(
        updated=_coerce_date(fields.get("updated")),
        focus=sections.get("focus", ""),
        next_step=sections.get("next", ""),
        open_questions=_status_bullets(sections.get("open questions", "")),
        decisions=_status_bullets(sections.get("decisions", "")),
    )


def _split_status_sections(body: str) -> dict[str, str]:
    """Split a Markdown body into ``## Heading`` sections, keyed by lowercase heading.

    Despite the name, this has nothing STATUS.md-specific in it — it is a
    plain ``## Heading`` splitter, so rule SMAIRT010 reuses it directly
    against a question unit's own README body to find its ``## Analysis
    plan`` section, rather than writing a second parser for the same shape.
    Structural only (foundation 5): this never inspects or judges the
    researcher's prose, only where one heading ends and the next begins.
    """
    sections: dict[str, str] = {}
    heading: str | None = None
    content: list[str] = []
    for line in body.splitlines():
        if line.startswith("## "):
            if heading is not None:
                sections[heading] = "\n".join(content).strip()
            heading = line[3:].strip().lower()
            content = []
        elif heading is not None:
            content.append(line)
    if heading is not None:
        sections[heading] = "\n".join(content).strip()
    return sections


def _status_bullets(text: str) -> tuple[str, ...]:
    """Pull the ``- item`` bullet lines out of one STATUS.md section's text.

    Used for the "Open questions" and "Decisions" sections, which are
    written as a Markdown bullet list. Non-bullet lines are dropped rather
    than raising, since this is reading free-text prose (foundation 5: never
    judge the researcher's prose) — a section that isn't a tidy bullet list
    just yields fewer (or zero) items instead of erroring.
    """
    items = []
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("-"):
            stripped = stripped[1:].strip()
        if stripped:
            items.append(stripped)
    return tuple(items)


@dataclass(frozen=True)
class _Unit:
    """A parsed (or unparseable) unit folder under experiments/, for internal reuse.

    ``body`` (the README's free-text half, below the frontmatter block) is
    carried here too, not just ``fields`` — rule SMAIRT010 needs it to check
    the ``## Analysis plan`` section, and reading it once here means that
    rule doesn't re-read every README a second time on its own.
    """

    path: Path
    rel: str
    error: str | None
    fields: dict[str, Any]
    body: str
    kind: UnitKind | None
    status: str | None


def run_checks(project_root: Path) -> CheckReport:
    """Run every WP2 rule against the project at ``project_root``. Read-only.

    This is the one function that ties every rule together (thirteen finding
    rules, SMAIRT001-013, plus five advisory suggestions, SMAIRT101-105): it
    loads every unit once (:func:`_load_units`), then hands that same list to
    each rule function in turn, collecting their findings/suggestions into
    one report. To add a new rule, write a ``_check_*`` (findings) or
    ``_suggest_*`` (suggestions) function following the pattern below and
    call it from here — see docs/ARCHITECTURE.md.
    """
    units = _load_units(project_root)

    findings: list[Finding] = []
    findings += _check_project_config(project_root)
    findings += _check_frontmatter_schema(units)
    findings += _check_evidence_pointers(project_root, units)
    findings += _check_receipt_completeness(units)

    suggestions: list[Suggestion] = []
    if project_module.is_git_work_tree(project_root):
        findings += _check_log_immutability(project_root, units)
    elif not _git_opt_out_recorded(project_root):
        # No Git, no history to check for edits after the fact -- rule
        # SMAIRT004 simply can't run, so we say so once (SMAIRT101) instead
        # of silently skipping it. Unless the researcher already told
        # `smairt new` they were choosing no Git on purpose (DG-5, see
        # :func:`_git_opt_out_recorded`) -- SMAIRT101 exists to catch an
        # ACCIDENT (a project nobody ever `git init`'d), and a recorded
        # choice is not one.
        suggestions.append(
            Suggestion(
                SUGGEST_GIT_UNAVAILABLE,
                ".",
                "not a Git repository: raw-log immutability under logs/ cannot be verified.",
            )
        )

    findings += _check_status_drift(project_root, units)
    findings += _check_structure_drift(project_root, units)
    findings += _check_missing_readme_folders(project_root)
    findings += _check_closed_question_completeness(units)
    findings += _check_prompted_by(project_root, units)
    findings += _check_prompted_by_cycle(project_root, units)
    findings += _check_hypothesis_nonempty(units)
    findings += _check_analysis_plan_on_close(units)

    suggestions += _suggest_hpc(project_root, units)
    suggestions += _suggest_grouping(units)
    suggestions += _suggest_paper_overlay(project_root)
    suggestions += _suggest_dataset_locations(project_root)

    return CheckReport(findings=tuple(findings), suggestions=tuple(suggestions))


# --- loading -----------------------------------------------------------------


def _load_units(project_root: Path) -> list[_Unit]:
    """Read every unit folder under ``experiments/`` into a list of :class:`_Unit`.

    This is the single place every rule below gets its unit data from, so
    each rule function only has to loop over an already-parsed list instead
    of re-reading the filesystem itself. A unit whose README fails to parse
    still becomes a ``_Unit`` (with ``error`` set and ``kind``/``status`` left
    ``None``) rather than being skipped — that's what lets rule 1
    (frontmatter schema) report it as a SMAIRT001 finding.
    """
    experiments_dir = project_root / "experiments"
    if not experiments_dir.is_dir():
        return []

    units: list[_Unit] = []
    for entry in sorted(experiments_dir.iterdir(), key=lambda item: item.name):
        readme = entry / "README.md"
        if not entry.is_dir() or not readme.is_file():
            continue
        rel = str(entry.relative_to(project_root))
        try:
            fields, body = frontmatter.read(readme)
        except frontmatter.FrontmatterError as error:
            units.append(
                _Unit(
                    path=entry,
                    rel=rel,
                    error=str(error),
                    fields={},
                    body="",
                    kind=None,
                    status=None,
                )
            )
            continue

        kind: UnitKind | None
        try:
            kind = UnitKind(fields.get("kind"))
        except ValueError:
            kind = None
        status = fields.get("status")
        units.append(
            _Unit(
                path=entry,
                rel=rel,
                error=None,
                fields=fields,
                body=body,
                kind=kind,
                status=str(status) if status is not None else None,
            )
        )
    return units


# --- project identity (rule SMAIRT011) ----------------------------------------

_PROJECT_CONFIG_REQUIRED_FIELDS = ("name", "researcher", "description")


def _git_opt_out_recorded(project_root: Path) -> bool:
    """Did the researcher tell ``smairt new`` "no Git" on purpose (DG-5)?

    Reads ``smairt.yaml``'s ``settings.git`` the same defensive way
    :func:`smairt.connect.read_strict_hooks` reads ``settings.strict_hooks``:
    through :func:`smairt.project.read_project_config`, falling back to
    ``False`` (i.e. "no recorded opt-out, act as before") on anything short of
    finding the key explicitly set to ``False`` -- a missing/unparseable/
    wrong-shaped ``smairt.yaml`` degrades exactly the way it already does for
    every other advisory-channel read in this codebase (see the module
    docstring's "DG-1's degrade policy" bullet); this is a *read* falling back
    to a safe default, not a write that silently failed, so no warning is
    owed here even when the fallback fires.

    ``settings.git`` is absent from the vast majority of projects (only
    ``smairt new --no-git``, or answering "no" at its prompt, ever writes it —
    see :func:`smairt.project.render_identity`), and absent is read as "no
    opt-out recorded", never as an opt-out itself: a project that predates
    this field, or was created with Git enabled, must keep getting SMAIRT101
    exactly as before once it genuinely has no ``.git`` to inspect (a
    researcher who deleted ``.git`` by hand, say). Only an explicit ``git:
    false`` counts -- checked with ``is False`` rather than plain falsiness,
    so a YAML quirk that parses ``git:`` to something else falsy-but-not-
    boolean (an empty string from a stray hand-edit, for instance) reads as
    "not a recognized opt-out" rather than silently suppressing a real
    finding-adjacent signal on a technicality.
    """
    config = project_module.read_project_config(project_root)
    if config.data is None:
        return False
    settings = config.data.get("settings")
    if not isinstance(settings, dict):
        return False
    return settings.get("git") is False


def _check_project_config(project_root: Path) -> list[Finding]:
    """Rule SMAIRT011: the project's own smairt.yaml must be a usable identity file.

    Every unit README gets SMAIRT001's coverage; before this rule existed,
    the project's OWN identity file got none — a corrupt or gutted
    ``smairt.yaml`` reported a perfectly healthy project (DG-1). A YAML
    SYNTAX error never reaches this function at all in normal use: every
    command already fails fast on that, at
    :func:`smairt.project.find_project_root`, before `run_checks` is even
    called — see the module docstring's "Judgment calls" section. What
    reaches here is a file that parses fine but is empty, isn't a mapping,
    or is missing one of the three identity fields a researcher actually
    fills in (see :data:`_PROJECT_CONFIG_REQUIRED_FIELDS` and the module
    docstring for why exactly those three).

    Emits at most one finding for the whole file, naming every problem found
    together, so the "here's what a correct file looks like" block that
    closes the message (the hard requirement DG-1 sets) appears once, not
    once per missing field.
    """
    config = project_module.read_project_config(project_root)
    example = project_module.example_smairt_yaml()

    if config.data is None:
        assert config.problem is not None
        return [
            Finding(
                RULE_PROJECT_CONFIG,
                ERROR,
                "smairt.yaml",
                f"{config.problem}.\n\nA correct smairt.yaml looks like this:\n\n{example}",
            )
        ]

    problems = [
        f"no `{field}:` field (or it is present but empty)"
        for field in _PROJECT_CONFIG_REQUIRED_FIELDS
        if not str(config.data.get(field, "")).strip()
    ]
    if not problems:
        return []
    return [
        Finding(
            RULE_PROJECT_CONFIG,
            ERROR,
            "smairt.yaml",
            "smairt.yaml is missing required field(s): "
            + "; ".join(problems)
            + f".\n\nA correct smairt.yaml looks like this:\n\n{example}",
        )
    ]


# --- rule 1: frontmatter schema ----------------------------------------------


def _check_frontmatter_schema(units: list[_Unit]) -> list[Finding]:
    """Rule SMAIRT001: every unit's frontmatter must parse and match its schema.

    Checked in order, each guarded by ``continue`` so a badly broken unit
    doesn't also get flooded with follow-on findings that wouldn't make
    sense: (1) does the frontmatter parse at all (caught earlier, by
    :func:`_load_units`); (2) is ``kind:`` a recognized value (``stage`` or
    ``question``). Once both of those pass, (3) ``status:`` and (4) every
    required field (from :mod:`smairt.units`) are checked independently, so
    a unit can rack up several findings at once for those two.
    """
    findings: list[Finding] = []
    for unit in units:
        readme_rel = f"{unit.rel}/README.md"

        # Every finding in this rule shares the same id and severity; only the
        # message changes, so a tiny local helper keeps each check below to
        # one line instead of a five-line Finding(...) call.
        def flag(message: str) -> None:
            findings.append(Finding(RULE_FRONTMATTER, ERROR, readme_rel, message))

        if unit.error is not None:
            flag(f"frontmatter block is missing or malformed: {unit.error}")
            continue
        if unit.kind is None:
            flag(f"kind {unit.fields.get('kind')!r} is not a recognized unit kind")
            continue
        allowed = units_module.allowed_statuses(unit.kind)
        if unit.status not in allowed:
            flag(
                f"status {unit.status!r} is not legal for kind "
                f"'{unit.kind.value}' (expected one of {list(allowed)})"
            )
        for field in units_module.required_fields(unit.kind):
            if field not in unit.fields:
                flag(f"missing required field '{field}'")
    return findings


# --- rule 2: evidence pointers resolve ---------------------------------------


def _as_targets(value: Any) -> list[str]:
    """Normalize a frontmatter pointer field into a list of path strings.

    A pointer field (``script:``, ``log:``, ``outputs:``, ``paths:``) can be
    written as a single string or as a YAML list — this treats both the same
    way, dropping blanks so an empty ``log: ""`` becomes an empty list rather
    than a list containing one blank string.
    """
    if isinstance(value, str):
        stripped = value.strip()
        return [stripped] if stripped else []
    if isinstance(value, list):
        return [str(item).strip() for item in value if str(item).strip()]
    return []


def _is_closed(kind: UnitKind, status: str | None) -> bool:
    """Is this unit "done" — no longer expected to change?

    A closed unit is held to a stricter standard (rule SMAIRT002: its
    script:/log: pointers must actually exist, not just be plausible).
    "Closed" means a different set of statuses for each kind: a stage is
    closed when frozen or dead-end; a question is closed by any status other
    than open (supported/refuted/inconclusive/dead-end).
    """
    if kind is UnitKind.stage:
        return status in _CLOSED_STAGE_STATUSES
    return status in _CLOSED_QUESTION_STATUSES


def _is_inside(candidate: Path, project_root: Path) -> bool:
    """Does ``candidate`` still land inside ``project_root`` once ``../`` is worked out?

    Uses :meth:`Path.resolve` on both sides so the comparison is made on real,
    symlink-free paths rather than on the text of the path — ``a/../b`` and
    ``b`` are the same place, and only ``resolve()`` knows that. Called with
    ``strict=False`` semantics deliberately: a pointer at a path that does not
    exist yet still needs its *location* judged, and "outside the project" is
    the more useful answer than "missing".
    """
    try:
        resolved_root = project_root.resolve()
        return resolved_root == candidate.resolve() or resolved_root in candidate.resolve().parents
    except OSError:
        # An unreadable or cyclic symlink on the way out: treat as not resolved
        # rather than letting an OSError escape a read-only audit.
        return False


def _pointer_resolves(
    unit_path: Path, project_root: Path, field: str, target: str, closed: bool
) -> bool:
    """Does this one pointer field's target actually exist on disk?

    Example: ``script: analysis.py`` resolves if ``analysis.py`` exists next
    to the unit's README. Returns ``False`` (a finding) if not — with one
    exception for not-yet-run questions, explained below.

    An absolute ``target`` is never treated as resolved, even if it happens to
    exist on the machine. This is deliberate, not an oversight: in
    ``pathlib``, ``base / target`` silently discards ``base`` entirely when
    ``target`` is absolute (``Path("/project") / "/etc/hosts" ==
    Path("/etc/hosts")``), which would let an absolute ``--ref``/``paths:``
    value (or a hand-typed ``script:``/``log:``/``outputs:``) resolve against
    the whole filesystem instead of the project root/unit folder it's
    documented to resolve against — silently passing `smairt check` for a
    pointer that has actually escaped the project. Every pointer field is
    documented as project-root- or unit-relative, never as an absolute
    filesystem path, so rejecting one here (as "does not resolve", the same
    finding a broken relative path gets) is the correct reading of the
    contract, not a new restriction.

    A *relative* target that climbs out of the project with ``../`` is
    refused for exactly the same reason. ``paths: ../../../../etc/hosts``
    is not absolute, so the check above lets it through, and it resolves to
    a real file — so it passed cleanly while pointing at something the
    project does not contain. Absolute and ``../``-escaping targets are two
    spellings of one mistake, and both have to be caught here, not just the
    one that looks like an escape.
    """
    # A reference unit's `paths:` (case 3, spec Part II) names pre-existing
    # paths relative to the PROJECT ROOT, not the unit folder — it points
    # elsewhere in the tree, unlike script:/log:/outputs: which are unit-local.
    base = project_root if field == "paths" else unit_path
    if Path(target).is_absolute():
        return False
    candidate = base / target
    if not _is_inside(candidate, project_root):
        return False
    if candidate.exists():
        return True
    if field == "log" and not closed:
        # `smairt unit new question` pre-fills log: with the filename the probe
        # is expected to write. For an open/active unit that hasn't run yet,
        # the containing logs/ folder existing is enough to call it resolved.
        return candidate.parent.is_dir()
    return False


def _check_evidence_pointers(project_root: Path, units: list[_Unit]) -> list[Finding]:
    """Rule SMAIRT002: every evidence pointer must point at something real.

    Walks each of the four pointer fields (``script:``, ``log:``,
    ``outputs:``, ``paths:``) on every unit. An empty pointer is only a
    problem if the unit is closed and the field is script:/log: (an open
    unit is allowed to not have run yet); a non-empty pointer that doesn't
    resolve to a real path is always a problem, via :func:`_pointer_resolves`.
    """
    findings: list[Finding] = []
    for unit in units:
        if unit.kind is None:
            continue
        readme_rel = f"{unit.rel}/README.md"

        def flag(message: str) -> None:
            findings.append(Finding(RULE_EVIDENCE_POINTERS, ERROR, readme_rel, message))

        closed = _is_closed(unit.kind, unit.status)
        for field in _POINTER_FIELDS:
            if field not in unit.fields:
                continue
            targets = _as_targets(unit.fields[field])
            if not targets:
                # An empty pointer only matters once the unit is closed --
                # see _is_closed's docstring for why "closed" differs by kind.
                if closed and field in ("script", "log"):
                    flag(f"closed unit's '{field}:' is empty")
                continue
            for target in targets:
                if not _pointer_resolves(unit.path, project_root, field, target, closed):
                    flag(f"'{field}: {target}' does not resolve to an existing path")
    return findings


# --- rule 3: receipt completeness --------------------------------------------


def _check_receipt_completeness(units: list[_Unit]) -> list[Finding]:
    """Rule SMAIRT003: a "receipt" unit (``tool:`` set) must record its receipt fully.

    A unit becomes a receipt the moment its frontmatter has a non-empty
    ``tool:`` field (see :func:`smairt.units.create_stage`'s ``receipt=``
    option). Once it is one, three things are required: a non-blank
    ``tool_version:``, a non-blank ``command:``, and a ``log:`` that both is
    set AND points at a file that exists — unlike rule SMAIRT002, a receipt's
    log is never given the "not run yet" pass, because pointing at an outside
    tool's output only makes sense once that output exists.
    """
    findings: list[Finding] = []
    for unit in units:
        if unit.kind is None:
            continue
        tool = unit.fields.get("tool")
        if not tool:
            continue
        readme_rel = f"{unit.rel}/README.md"

        def flag(message: str) -> None:
            findings.append(Finding(RULE_RECEIPT_COMPLETENESS, ERROR, readme_rel, message))

        if not str(unit.fields.get("tool_version", "")).strip():
            flag("receipt unit ('tool:' set) has an empty 'tool_version:'")
        if not str(unit.fields.get("command", "")).strip():
            flag("receipt unit ('tool:' set) has an empty 'command:'")
        targets = _as_targets(unit.fields.get("log"))
        if not targets:
            flag("receipt unit ('tool:' set) has no 'log:' pointer")
        else:
            missing = [target for target in targets if not (unit.path / target).exists()]
            if missing:
                flag(f"receipt unit's log does not exist: {', '.join(missing)}")
    return findings


# --- rule 4: raw-log immutability --------------------------------------------


def _git_modified_paths(project_root: Path, rel_dir: Path) -> set[str]:
    """Paths under ``rel_dir`` that changed after the commit that first added them.

    Two sources, unioned: commits where the file already existed and was
    modified (``--diff-filter=M`` excludes the add itself), and any working-tree
    or staged edit to an already-committed file that hasn't been committed yet
    (``git diff HEAD``) — the immutability violation someone is most likely to
    still be looking at when `smairt check` runs.
    """
    modified: set[str] = set()

    history = subprocess.run(
        ["git", "log", "--diff-filter=M", "--name-only", "--pretty=format:", "--", str(rel_dir)],
        cwd=project_root,
        capture_output=True,
        text=True,
        check=False,
    )
    if history.returncode == 0:
        modified.update(line.strip() for line in history.stdout.splitlines() if line.strip())

    working_tree = subprocess.run(
        ["git", "diff", "--name-only", "HEAD", "--", str(rel_dir)],
        cwd=project_root,
        capture_output=True,
        text=True,
        check=False,
    )
    if working_tree.returncode == 0:
        modified.update(line.strip() for line in working_tree.stdout.splitlines() if line.strip())

    return modified


def _check_log_immutability(project_root: Path, units: list[_Unit]) -> list[Finding]:
    """Rule SMAIRT004: a file under a unit's ``logs/`` must never be edited after it lands.

    Raw logs are the ground truth a unit's conclusions are checked against;
    editing one after the fact would let someone rewrite the evidence. This
    asks Git (via :func:`_git_modified_paths`) which log files have a
    modification recorded after their first commit, and flags every one
    found. Only runs when :func:`smairt.project.is_git_work_tree` says Git history
    is available.
    """
    findings: list[Finding] = []
    for unit in units:
        logs_dir = unit.path / "logs"
        if not logs_dir.is_dir():
            continue
        rel_logs = logs_dir.relative_to(project_root)
        for rel_path in sorted(_git_modified_paths(project_root, rel_logs)):
            absolute = project_root / rel_path
            if absolute.is_file() and absolute.name != ".gitkeep":
                findings.append(
                    Finding(
                        RULE_LOG_IMMUTABILITY,
                        ERROR,
                        rel_path,
                        "log file was modified after being committed; raw evidence must be immutable",
                    )
                )
    return findings


# --- rule 5: STATUS drift ----------------------------------------------------


def _coerce_date(value: object) -> date | None:
    """Best-effort conversion of a YAML-parsed value into a plain ``date``.

    PyYAML usually parses an unquoted ``2026-08-12`` into a real ``date`` (or
    ``datetime``) already, but a hand-edited or oddly quoted value could come
    through as a string, or as something else entirely. Returns ``None``
    (rather than raising) for anything that isn't a recognizable date, since
    a malformed ``updated:`` shouldn't crash the whole check run.
    """
    if isinstance(value, datetime):
        return value.date()
    if isinstance(value, date):
        return value
    if isinstance(value, str):
        try:
            return date.fromisoformat(value)
        except ValueError:
            return None
    return None


def _newest_mtime_date(unit_dir: Path) -> date:
    """The calendar date of the most recently modified file inside ``unit_dir``.

    Walks every file under the unit (skipping ``.gitkeep`` placeholders) and
    takes the latest modification time, truncated to a date — matching the
    day-granularity STATUS.md's ``updated:`` field already uses, so the two
    are comparable. Falls back to the unit folder's own mtime if it somehow
    has no files at all (e.g. a fresh reference unit).
    """
    newest: float | None = None
    for path in unit_dir.rglob("*"):
        if not path.is_file() or path.name == ".gitkeep":
            continue
        mtime = path.stat().st_mtime
        if newest is None or mtime > newest:
            newest = mtime
    if newest is None:
        newest = unit_dir.stat().st_mtime
    return datetime.fromtimestamp(newest).date()


def _check_status_drift(project_root: Path, units: list[_Unit]) -> list[Finding]:
    """Rule SMAIRT005 (warning): flag units changed after STATUS.md was last updated.

    STATUS.md is the project's hand-maintained "what's going on" summary; if
    a unit has newer files than STATUS.md's own ``updated:`` date, that
    summary is probably stale. Skipped entirely if STATUS.md is missing,
    malformed, or has no ``updated:`` date to compare against.
    """
    status = read_status(project_root)
    if status is None or status.updated is None:
        return []

    findings: list[Finding] = []
    for unit in units:
        newest = _newest_mtime_date(unit.path)
        if newest > status.updated:
            findings.append(
                Finding(
                    RULE_STATUS_DRIFT,
                    WARNING,
                    unit.rel,
                    f"changed {newest.isoformat()}, after STATUS.md was last updated "
                    f"{status.updated.isoformat()}",
                )
            )
    return findings


# --- rule 6: structure drift --------------------------------------------------


def _adoption_known_folders(project_root: Path) -> frozenset[str]:
    """Read ``smairt.yaml``'s ``adoption.known_folders`` (empty if absent/unreadable).

    ``smairt adopt`` records the top-level directories that already existed at
    adoption time here (Part II case 3); rule 6 treats them as recognized so an
    adopted project passes `smairt check` clean immediately. Folders appearing
    AFTER adoption are not in this list and still warn as usual.

    Goes through :func:`smairt.project.read_project_config` rather than
    parsing ``smairt.yaml`` itself, and stays silent (an empty result, same
    as "no adoption record") when that fails — DG-1's degrade policy: the
    file being unreadable is already surfaced once, systematically, by
    fail-fast or rule SMAIRT011, so this one enhancement quietly not
    applying is not a second thing to warn about. See the module docstring's
    "Judgment calls" section.
    """
    config = project_module.read_project_config(project_root)
    if config.data is None:
        return frozenset()
    adoption = config.data.get("adoption")
    if not isinstance(adoption, dict):
        return frozenset()
    folders = adoption.get("known_folders")
    if not isinstance(folders, list):
        return frozenset()
    return frozenset(str(item) for item in folders)


def _check_structure_drift(project_root: Path, units: list[_Unit]) -> list[Finding]:
    """Rule SMAIRT006 (warning): flag files/folders outside the expected project shape.

    Two separate checks, both warnings rather than errors (the project still
    works, it just doesn't match the documented shape): (1) any file sitting
    loose directly under ``experiments/`` instead of inside a unit folder;
    (2) any top-level folder that isn't one of the standard scaffold folders
    (background/data/scripts/experiments/results/hpc) or one this project's
    ``smairt adopt`` already recorded as pre-existing (see
    :func:`_adoption_known_folders`).

    DG-3 sharpens case (2)'s message when the unrecognized folder itself
    contains a ``smairt.yaml`` — that is specifically a SECOND SMAIRT project
    nested inside this one (most likely created by ``smairt new`` run from
    inside this project, which now warns about this at creation time too —
    see :func:`smairt.project.find_enclosing_project`), not just some
    unfamiliar folder, and naming that cause directly saves the researcher
    from having to work it out themselves the way the friction walk's
    reproduction did.
    """
    findings: list[Finding] = []
    experiments_dir = project_root / "experiments"
    if experiments_dir.is_dir():
        for entry in sorted(experiments_dir.iterdir(), key=lambda item: item.name):
            if entry.is_dir():
                continue
            if entry.name == "README.md":
                continue
            findings.append(
                Finding(
                    RULE_STRUCTURE_DRIFT,
                    WARNING,
                    f"experiments/{entry.name}",
                    "file is loose directly under experiments/, outside any unit folder",
                )
            )
    if project_root.is_dir():
        recognized = _KNOWN_TOP_LEVEL_DIRS | _adoption_known_folders(project_root)
        for entry in sorted(project_root.iterdir(), key=lambda item: item.name):
            if not entry.is_dir() or entry.name.startswith("."):
                continue
            if entry.name in recognized:
                continue
            if (entry / "smairt.yaml").is_file():
                message = (
                    f"top-level folder '{entry.name}' is itself a SMAIRT project (it has its "
                    "own smairt.yaml) nested inside this one -- commands run from inside it "
                    "use ITS smairt.yaml, not this project's; move it out from under "
                    f"{project_root.name}/, or ignore this warning if the nesting is intentional."
                )
            else:
                message = (
                    "top-level folder is not part of the known scaffold "
                    "(background/, data/, scripts/, experiments/, results/, hpc/) "
                    "or this adopted project's known_folders"
                )
            findings.append(Finding(RULE_STRUCTURE_DRIFT, WARNING, entry.name, message))
    return findings


# --- README-less unit folder (rule SMAIRT012) ---------------------------------


def _check_missing_readme_folders(project_root: Path) -> list[Finding]:
    """Rule SMAIRT012 (warning): a folder directly under experiments/ with no README.md.

    :func:`_load_units` (and :func:`smairt.index.scan_units`) both gate on
    ``entry.is_dir() and readme.is_file()`` — a folder failing that second
    half is silently skipped everywhere, so a researcher who created a
    folder by hand (or deleted its README) gets no signal their work is
    untracked (DG-2). Warning, not error or suggestion: the same severity as
    SMAIRT006 structure drift, the same class of problem (the project still
    "works", it just doesn't match a shape `smairt` can see). The message
    names the one supported fix (``smairt unit new``) rather than guessing
    whether this was meant to be a stage or a question.

    Skips dot-prefixed folders (``.ipynb_checkpoints/``, an editor's
    ``.git``-like scratch directory, ...) the same way
    :func:`_check_structure_drift`'s top-level scan does — those are tool
    artifacts a researcher didn't create on purpose, not untracked work, and
    flagging them would be noise rather than signal.
    """
    experiments_dir = project_root / "experiments"
    if not experiments_dir.is_dir():
        return []
    findings: list[Finding] = []
    for entry in sorted(experiments_dir.iterdir(), key=lambda item: item.name):
        if not entry.is_dir() or entry.name.startswith("."):
            continue
        if (entry / "README.md").is_file():
            continue
        findings.append(
            Finding(
                RULE_MISSING_README,
                WARNING,
                f"experiments/{entry.name}",
                "folder has no README.md, so it is invisible to check/status/index; "
                "`smairt unit new` is the only supported way to create a unit -- remove "
                "this folder if it was a mistake, or create a real unit for the work "
                "inside it.",
            )
        )
    return findings


# --- rule 7: closed-question completeness ------------------------------------


def _check_closed_question_completeness(units: list[_Unit]) -> list[Finding]:
    """Rule SMAIRT007: a closed question must record its verdict.

    "Closed" here means any question status other than open (supported,
    refuted, inconclusive, or dead-end) — the point of closing a question is
    to answer it, so a blank ``verdict:`` on a closed question means the
    answer was never actually written down.
    """
    findings: list[Finding] = []
    for unit in units:
        if unit.kind is not UnitKind.question:
            continue
        if unit.status not in _CLOSED_QUESTION_STATUSES:
            continue
        verdict = str(unit.fields.get("verdict", "")).strip()
        if not verdict:
            findings.append(
                Finding(
                    RULE_CLOSED_QUESTION,
                    ERROR,
                    f"{unit.rel}/README.md",
                    f"status '{unit.status}' requires a non-empty verdict",
                )
            )
    return findings


# --- rule 8: prompted_by resolves ---------------------------------------------


def _prompted_by_resolves(project_root: Path, target: str) -> bool:
    """Does ``prompted_by: target`` name a real unit — a folder with its own README.md?

    Mirrors the standard :func:`_pointer_resolves` already applies to a
    reference unit's ``paths:`` (project-root relative, not unit-relative,
    since ``prompted_by:`` names another unit under ``experiments/``, not a
    path local to this one). A bare folder that happens to share the name
    but has no README.md — e.g. one rule SMAIRT006 would separately flag as
    structure drift — does not count as "a real unit."

    An absolute ``target`` is never treated as resolved, for the same reason
    :func:`_pointer_resolves` rejects one: ``pathlib`` would silently discard
    every path segment built up so far and check the whole filesystem instead
    of ``experiments/``.
    """
    if Path(target).is_absolute():
        return False
    return (project_root / "experiments" / target / "README.md").is_file()


def _check_prompted_by(project_root: Path, units: list[_Unit]) -> list[Finding]:
    """Rule SMAIRT008: a question's prompted_by:, if set, must resolve to a real unit.

    ``prompted_by:`` (spec ticket 01, "sidequest lineage") records which unit's
    result raised this question — set only via ``smairt unit new question
    --from``, which already validates the target exists at creation (see
    :func:`smairt.units.create_question`). This rule is the backstop for
    every other way the field can go stale afterward: the origin unit gets
    renamed, moved, or (rarely) deleted by hand. The field is never required,
    so this only ever fires when it is present — an unset ``prompted_by:``
    is silent, exactly like an unset ``script:``/``log:`` on an open unit.
    """
    findings: list[Finding] = []
    for unit in units:
        if unit.kind is not UnitKind.question:
            continue
        target = str(unit.fields.get("prompted_by", "")).strip()
        if not target:
            continue
        if not _prompted_by_resolves(project_root, target):
            findings.append(
                Finding(
                    RULE_PROMPTED_BY,
                    ERROR,
                    f"{unit.rel}/README.md",
                    f"'prompted_by: {target}' does not resolve to a real unit under "
                    "experiments/; fix the folder name, or remove the field if this "
                    "question was not actually prompted by another unit's result.",
                )
            )
    return findings


def _check_prompted_by_cycle(project_root: Path, units: list[_Unit]) -> list[Finding]:
    """Rule SMAIRT013 (error): a prompted_by: chain that loops back on itself.

    Only reachable by hand-editing frontmatter (nothing ``smairt`` itself
    writes can create one: ``--from`` is validated at creation, and a
    project's units are only ever added, never reparented, by this tool) —
    but when it happens, rule SMAIRT008 alone reports the project as
    perfectly clean, because every link in a cycle DOES resolve to a real
    unit; only the graph as a whole is broken. :func:`smairt.index.
    _ordered_for_index` already has its own guard against this (verified
    under a hard 15-second timeout to never hang or crash) but that guard's
    job is only to still RENDER something; it silently drops the cycle from
    the lineage nesting with no message that anything was dropped. This
    function is a separate, from-scratch walk added purely to REPORT the
    same cycle that guard was silently working around — it does not call
    into, share state with, or change that function in any way.

    Builds one edge per question unit whose ``prompted_by:`` already
    resolves (see :func:`_prompted_by_resolves`) — a dangling link is
    SMAIRT008's finding, not a cycle candidate, so the two rules partition
    the same field's possible problems rather than double-reporting the same
    one. Because a question has at most one ``prompted_by:`` target, this
    graph has out-degree <= 1 everywhere (a "functional graph"), so a plain
    three-color walk (unvisited / in-progress / done) finds every cycle in
    O(n) with no recursion and no need for a general cycle-finding
    algorithm: following any node's single outgoing edge either runs off the
    end (no cycle), rejoins an already-fully-walked chain (no NEW cycle), or
    comes back to a node already ``in-progress`` in THIS walk -- which is
    exactly a cycle, read straight off the path collected so far.
    """
    edges: dict[str, str] = {}
    for unit in units:
        if unit.kind is not UnitKind.question:
            continue
        target = str(unit.fields.get("prompted_by", "")).strip()
        if target and _prompted_by_resolves(project_root, target):
            edges[unit.path.name] = target

    unvisited, in_progress, done = 0, 1, 2
    state: dict[str, int] = {}
    findings: list[Finding] = []

    for start in edges:
        if state.get(start, unvisited) != unvisited:
            continue
        path: list[str] = []
        node: str | None = start
        while node is not None and state.get(node, unvisited) == unvisited:
            state[node] = in_progress
            path.append(node)
            node = edges.get(node)
        if node is not None and state.get(node) == in_progress:
            cycle = path[path.index(node) :]
            loop = " -> ".join(f"experiments/{name}" for name in (*cycle, cycle[0]))
            findings.append(
                Finding(
                    RULE_PROMPTED_BY_CYCLE,
                    ERROR,
                    f"experiments/{cycle[0]}/README.md",
                    f"prompted_by: forms a cycle: {loop} -- a question cannot have "
                    "(even indirectly) been prompted by itself; break the loop by "
                    "removing or correcting one unit's prompted_by: field.",
                )
            )
        for name in path:
            state[name] = done
    return findings


# --- rule 9: hypothesis is non-empty ------------------------------------------


def _check_hypothesis_nonempty(units: list[_Unit]) -> list[Finding]:
    """Rule SMAIRT009: a question unit's hypothesis: must actually say something.

    Hypothesis-before-run is SMAIRT's central discipline for a question unit,
    but until this rule existed nothing checked that ``hypothesis:`` held
    real text — SMAIRT001 only checks that the key exists, and ``smairt unit
    new question`` fills a missing ``--hypothesis`` with ``""``, which passed
    clean (spec ticket 02 verified this empirically before deciding to close
    the gap). This rule fires for any status, open or closed — waiting until
    a question closes to demand its claim would let the claim get written
    after the result is already known, which is exactly the retrofitting
    hypothesis-before-run exists to prevent.

    Skips a unit whose ``hypothesis:`` key is missing entirely (as opposed to
    present-but-blank) — SMAIRT001 already reports that as a missing
    required field, so this rule only adds the case SMAIRT001 can't see: a
    present key with nothing in it. Also skips reference units (``paths:``
    present, case 3, spec Part II) — see the module docstring's "Judgment
    calls" section for why.
    """
    findings: list[Finding] = []
    for unit in units:
        if unit.kind is not UnitKind.question:
            continue
        if "paths" in unit.fields:
            continue
        if "hypothesis" not in unit.fields:
            continue
        hypothesis = str(unit.fields["hypothesis"]).strip()
        if not hypothesis:
            findings.append(
                Finding(
                    RULE_HYPOTHESIS_NONEMPTY,
                    ERROR,
                    f"{unit.rel}/README.md",
                    "hypothesis: is empty; write the one-line claim this question "
                    "tests before treating any run as evidence for or against it.",
                )
            )
    return findings


# --- rule 10: closed question needs a non-empty Analysis plan ----------------


def _check_analysis_plan_on_close(units: list[_Unit]) -> list[Finding]:
    """Rule SMAIRT010: a CLOSED question's '## Analysis plan' section must not be empty.

    "Closed" means the same set of statuses rule SMAIRT007 already uses
    (anything but open) — the moment a question closes is when the plan
    should already exist, so this is one more thing checked in the same edit
    that sets ``verdict:``, not a separate gate. Reuses
    :func:`_split_status_sections` against the unit's own README body
    (:attr:`_Unit.body`) rather than writing a second ``## Heading`` parser —
    see the module docstring's "Judgment calls" section. Skips reference
    units (``paths:`` present, case 3) for the same reason rule SMAIRT009
    does: adopted pre-existing work was never framed as a testable claim, so
    it has no analysis plan to have pre-specified.

    The rule matches on exact heading text (``## Analysis plan``), so a
    researcher who hand-renamed the heading (a typo, or trying to be more
    specific) would otherwise see the identical "requires a non-empty ...
    section" message a genuinely blank section gets — misleading, since they
    can see their own paragraph sitting right there under the renamed
    heading. The two cases get two different messages below: "no such
    heading" (fixable by putting the heading text back) vs. "heading found,
    body empty" (fixable by writing the plan).
    """
    findings: list[Finding] = []
    for unit in units:
        if unit.kind is not UnitKind.question:
            continue
        if unit.status not in _CLOSED_QUESTION_STATUSES:
            continue
        if "paths" in unit.fields:
            continue
        sections = _split_status_sections(unit.body)
        if "analysis plan" not in sections:
            findings.append(
                Finding(
                    RULE_ANALYSIS_PLAN,
                    ERROR,
                    f"{unit.rel}/README.md",
                    f"status '{unit.status}' requires a '## Analysis plan' section, "
                    "but no heading with that exact text was found -- if you renamed "
                    "it, rename it back to '## Analysis plan' (this rule matches the "
                    "heading text exactly).",
                )
            )
            continue
        plan = sections["analysis plan"]
        if not plan.strip():
            findings.append(
                Finding(
                    RULE_ANALYSIS_PLAN,
                    ERROR,
                    f"{unit.rel}/README.md",
                    f"status '{unit.status}' requires a non-empty '## Analysis plan' "
                    "section -- write what you measured and how you judged the "
                    "result before closing (amend it with '**Amended "
                    "YYYY-MM-DD:**' if the plan changed after it was written).",
                )
            )
    return findings


# --- rule 11: growth suggestions (advisory channel) ---------------------------


def _contains_slurm_content(unit_dir: Path) -> bool:
    """Does any file inside ``unit_dir`` mention ``sbatch`` (SLURM's submit command)?

    A crude but cheap text search, not a real SLURM script parser — good
    enough for the SMAIRT102 advisory, which is just a "you might want an
    hpc/ folder" nudge, not something a researcher needs to trust completely.
    """
    for path in unit_dir.rglob("*"):
        if not path.is_file() or path.name == ".gitkeep":
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        if "sbatch" in text.lower():
            return True
    return False


def _suggest_hpc(project_root: Path, units: list[_Unit]) -> list[Suggestion]:
    """Advisory SMAIRT102: nudge toward an ``hpc/`` folder if SLURM content shows up without one.

    Stops at the first unit with SLURM content (see :func:`_contains_slurm_content`)
    — this is a "notice the pattern" prompt, not an audit of every occurrence.
    """
    if (project_root / "hpc").is_dir():
        return []
    for unit in units:
        if _contains_slurm_content(unit.path):
            return [
                Suggestion(
                    SUGGEST_HPC,
                    unit.rel,
                    "contains SLURM/sbatch content but this project has no hpc/ folder; "
                    "consider adding one to hold submission templates.",
                )
            ]
    return []


def _question_slug_word(unit: _Unit) -> str | None:
    """The first word of a question unit's slug, for spotting a shared naming pattern.

    Example: folder ``2026-08-12_align-reads`` -> ``"align"``. A question
    folder is named ``date_slug``, and the slug's words are joined with
    ``-`` (see :mod:`smairt.text`), so splitting on ``_`` then ``-`` peels
    off exactly the leading word. Returns ``None`` if the name doesn't have
    the expected shape at all.
    """
    name = unit.path.name
    if "_" not in name:
        return None
    _prefix, slug = name.split("_", 1)
    if not slug:
        return None
    return slug.split("-", 1)[0]


def _suggest_grouping(units: list[_Unit]) -> list[Suggestion]:
    """Advisory SMAIRT103: nudge toward a grouping subfolder when 3+ questions share a leading word.

    Example: ``align-v1``, ``align-v2``, ``align-debug`` all start with
    "align" — three or more such questions might be a sign they'd read
    better grouped under a subfolder of experiments/. One suggestion per
    shared word, naming the first offending unit as the example.
    """
    groups: dict[str, list[str]] = {}
    for unit in units:
        if unit.kind is not UnitKind.question:
            continue
        word = _question_slug_word(unit)
        if not word:
            continue
        groups.setdefault(word, []).append(unit.rel)

    suggestions: list[Suggestion] = []
    for word, paths in sorted(groups.items()):
        if len(paths) >= 3:
            suggestions.append(
                Suggestion(
                    SUGGEST_GROUPING,
                    paths[0],
                    f"{len(paths)} question units share the leading word '{word}' "
                    f"({', '.join(paths)}); a grouping subfolder under experiments/ may be earned.",
                )
            )
    return suggestions


def _suggest_paper_overlay(project_root: Path) -> list[Suggestion]:
    """Advisory SMAIRT104: point at the (not-yet-built) Paper overlay if STATUS.md mentions paper work.

    A plain case-insensitive text search for "paper", "manuscript", or
    "figure legend" in STATUS.md — deliberately simple, since this is only a
    pointer to a deferred future feature, not a rule the researcher needs to
    satisfy.
    """
    status_path = project_root / "STATUS.md"
    if not status_path.is_file():
        return []
    text = status_path.read_text(encoding="utf-8", errors="ignore").lower()
    if any(word in text for word in _PAPER_WORDS):
        return [
            Suggestion(
                SUGGEST_PAPER_OVERLAY,
                "STATUS.md",
                "mentions paper/manuscript/figure-legend work; the Paper overlay is a "
                "deferred future capability, not yet supported.",
            )
        ]
    return []


def _dataset_missing_locations(dataset_dir: Path) -> bool:
    """Does this ``data/<x>/`` folder lack a usable ``locations:`` record?

    True when there is no ``README.md`` at all, the README has no
    frontmatter block, or its frontmatter has a ``locations:`` field that is
    missing, not a list, or an empty list — any of these means `smairt data
    list` would report zero locations for this dataset, i.e. nobody has
    written down where its bytes actually are.
    """
    readme = dataset_dir / "README.md"
    if not readme.is_file():
        return True
    try:
        fields, _body = frontmatter.read(readme)
    except frontmatter.FrontmatterError:
        return True
    locations = fields.get("locations")
    return not isinstance(locations, list) or not locations


def _suggest_dataset_locations(project_root: Path) -> list[Suggestion]:
    """Advisory SMAIRT105: nudge toward recording where a dataset's bytes live.

    Stops at the first ``data/<x>/`` subfolder with no usable ``locations:``
    record (see :func:`_dataset_missing_locations`) — like the rest of rule
    8, this is a "notice the pattern" prompt (point at `smairt data list` /
    `smairt data new` / `smairt data locate`), not a per-dataset audit; see
    the module docstring's "Judgment calls" section for why once-per-run was
    chosen over once-per-dataset.
    """
    data_dir = project_root / "data"
    if not data_dir.is_dir():
        return []
    for entry in sorted(data_dir.iterdir(), key=lambda item: item.name):
        if not entry.is_dir():
            continue
        if _dataset_missing_locations(entry):
            return [
                Suggestion(
                    SUGGEST_DATASET_LOCATIONS,
                    f"data/{entry.name}",
                    "has no recorded locations: entry; run `smairt data new` (if this "
                    "isn't a dataset yet) or `smairt data locate` to record where its "
                    "bytes actually live.",
                )
            ]
    return []


# --- output rendering ---------------------------------------------------------


def render_human(report: CheckReport) -> str:
    """Render findings grouped by severity, then suggestions, then a summary line."""
    errors = [finding for finding in report.findings if finding.severity == ERROR]
    warnings = [finding for finding in report.findings if finding.severity == WARNING]

    lines: list[str] = []
    if errors:
        lines.append("Errors:")
        lines.extend(f"  {finding.id} {finding.path}: {finding.message}" for finding in errors)
    if warnings:
        lines.append("Warnings:")
        lines.extend(f"  {finding.id} {finding.path}: {finding.message}" for finding in warnings)
    if not report.findings:
        lines.append("No errors or warnings.")

    if report.suggestions:
        lines.append("")
        lines.append("Suggestions:")
        lines.extend(
            f"  {suggestion.id} {suggestion.path}: {suggestion.message}"
            for suggestion in report.suggestions
        )

    lines.append("")
    lines.append(
        f"{len(errors)} error(s), {len(warnings)} warning(s), "
        f"{len(report.suggestions)} suggestion(s)."
    )
    return "\n".join(lines)


def to_json(report: CheckReport) -> dict[str, Any]:
    """Render ``report`` as the ``--json`` payload: findings, suggestions, summary."""
    errors = sum(1 for finding in report.findings if finding.severity == ERROR)
    warnings = sum(1 for finding in report.findings if finding.severity == WARNING)
    return {
        "findings": [asdict(finding) for finding in report.findings],
        "suggestions": [asdict(suggestion) for suggestion in report.suggestions],
        "summary": {
            "errors": errors,
            "warnings": warnings,
            "suggestions": len(report.suggestions),
            "exit_code": report.exit_code,
        },
    }
