"""``smairt check`` — the state contract (WP2).

Tier-2 enforcement (spec Part I, foundation 2): what tooling cannot generate at
creation time (tier 1), it verifies mechanically here. Derived-first (foundation
3): this module reads frontmatter, the filesystem, and Git; it never maintains a
database of its own, and it never writes anything — the one deliberate exception
elsewhere in the codebase, ``results/INDEX.md``, is regenerated by
:mod:`smairt.index`, not here.

Public entry point: :func:`run_checks`, returning a :class:`CheckReport`.

:func:`read_status` is the single reader of ``STATUS.md`` (frontmatter *and* its
``## Heading`` body sections) — reused by rule 5 below and by ``smairt status`` (WP3).

Finding IDs
-----------
Every rule below carries exactly one stable ID (the *rule* is the unit of
identity, not each way it can be violated — a rule's ``message`` text carries
the specifics). IDs are referenced by tests and, later, by WP4's hooks, so they
must not be renumbered once shipped.

Findings (severity error/warning; each instance affects the process exit code)::

    SMAIRT001  Frontmatter schema invalid: block missing/malformed, kind not
               recognized, status illegal for that kind, or a required field
               (per smairt.units) absent.                              [error]
    SMAIRT002  An evidence pointer (script:/log:/outputs:/paths:) does not
               resolve, or a CLOSED unit's script:/log: is empty.       [error]
    SMAIRT003  Receipt completeness: a unit with tool: set has an empty
               tool_version:, empty command:, or a log: that does not exist.
                                                                          [error]
    SMAIRT004  Raw-log immutability: a file under a unit's logs/ was modified
               in a later commit than the one that added it.            [error]
    SMAIRT005  STATUS drift: STATUS.md's updated: is older than a unit that
               has changed since.                                     [warning]
    SMAIRT006  Structure drift: a file loose directly under experiments/
               (outside any unit folder), or an unrecognized top-level
               project folder.                                        [warning]
    SMAIRT007  Closed-question completeness: status in {supported, refuted,
               inconclusive, dead-end} with an empty verdict:.          [error]

Advisory suggestions (a separate channel; never affect the exit code)::

    SMAIRT101  Git is unavailable, so raw-log immutability (rule SMAIRT004)
               could not be checked at all — one note, not per-file.
    SMAIRT102  SLURM/sbatch content found in a unit but the project has no
               hpc/ folder yet.
    SMAIRT103  Three or more question units share a leading slug word: a
               grouping subfolder may be earned.
    SMAIRT104  STATUS.md mentions paper/manuscript/figure-legend work: a
               pointer to the (deferred) Paper overlay.

Judgment calls a reviewer should know about
--------------------------------------------
* ``smairt unit new question`` pre-fills ``log:`` with the filename the probe
  is expected to write (``logs/<slug>.log``) before it has run. Rule SMAIRT002
  treats that as resolved for an OPEN/ACTIVE unit as long as the containing
  ``logs/`` folder exists — only a CLOSED unit is held to the exact file
  existing. This is what lets a freshly created, not-yet-run question pass
  check with zero findings (WP1's own acceptance criterion).
* Rule SMAIRT004 (log immutability) is skipped, in favor of the single
  SMAIRT101 advisory, whenever the project is not inside a Git work tree —
  this keeps `smairt check` usable before a researcher runs ``git init``.
* Rule SMAIRT005 (STATUS drift) compares calendar dates only (a file's mtime
  truncated to a date vs. STATUS.md's ``updated:`` date), not timestamps —
  matching the day-granularity the frontmatter schemas already use.
* Rule 8's growth suggestions each fire at most once per run (naming the
  first offending unit, not every one) — they are prompts to notice a
  pattern, not a per-file audit.
"""

from __future__ import annotations

import shutil
import subprocess
from dataclasses import asdict, dataclass
from datetime import date, datetime
from pathlib import Path
from typing import Any

from smairt import frontmatter
from smairt import units as units_module
from smairt.units import UnitKind

ERROR = "error"
WARNING = "warning"

RULE_FRONTMATTER = "SMAIRT001"
RULE_EVIDENCE_POINTERS = "SMAIRT002"
RULE_RECEIPT_COMPLETENESS = "SMAIRT003"
RULE_LOG_IMMUTABILITY = "SMAIRT004"
RULE_STATUS_DRIFT = "SMAIRT005"
RULE_STRUCTURE_DRIFT = "SMAIRT006"
RULE_CLOSED_QUESTION = "SMAIRT007"

SUGGEST_GIT_UNAVAILABLE = "SMAIRT101"
SUGGEST_HPC = "SMAIRT102"
SUGGEST_GROUPING = "SMAIRT103"
SUGGEST_PAPER_OVERLAY = "SMAIRT104"

_POINTER_FIELDS = ("script", "log", "outputs", "paths")
_KNOWN_TOP_LEVEL_DIRS = frozenset(
    {"background", "data", "scripts", "experiments", "results", "hpc"}
)
_CLOSED_STAGE_STATUSES = frozenset({"frozen", "dead-end"})
_CLOSED_QUESTION_STATUSES = frozenset({"supported", "refuted", "inconclusive", "dead-end"})
_PAPER_WORDS = ("paper", "manuscript", "figure legend")


@dataclass(frozen=True)
class Finding:
    """One violation of the state contract. ``severity`` is ``error`` or ``warning``."""

    id: str
    severity: str
    path: str
    message: str


@dataclass(frozen=True)
class Suggestion:
    """One growth-channel note. Advisory only: never affects the exit code."""

    id: str
    path: str
    message: str


@dataclass(frozen=True)
class CheckReport:
    """The full result of :func:`run_checks`."""

    findings: tuple[Finding, ...]
    suggestions: tuple[Suggestion, ...]

    @property
    def exit_code(self) -> int:
        return 1 if self.findings else 0


@dataclass(frozen=True)
class StatusDocument:
    """The parsed contents of STATUS.md — the project's one hand-maintained ledger
    (Part I, foundation 3). This is the single reader for STATUS.md: :func:`run_checks`
    consults only ``updated`` (rule 5, STATUS drift); ``smairt status`` (WP3) reads the
    rest to print Focus/Next/Open questions. Keeping both behind :func:`read_status`
    means there is exactly one place that parses this file.
    """

    updated: date | None
    focus: str
    next_step: str
    open_questions: tuple[str, ...]
    decisions: tuple[str, ...]


def read_status(project_root: Path) -> StatusDocument | None:
    """Read and parse ``STATUS.md``, or ``None`` if it is absent or malformed."""
    status_path = project_root / "STATUS.md"
    if not status_path.is_file():
        return None
    try:
        fields, body = frontmatter.read(status_path)
    except frontmatter.FrontmatterError:
        return None
    sections = _split_status_sections(body)
    return StatusDocument(
        updated=_coerce_date(fields.get("updated")),
        focus=sections.get("focus", ""),
        next_step=sections.get("next", ""),
        open_questions=_status_bullets(sections.get("open questions", "")),
        decisions=_status_bullets(sections.get("decisions", "")),
    )


def _split_status_sections(body: str) -> dict[str, str]:
    """Split a STATUS.md body into ``## Heading`` sections, keyed by lowercase heading.

    Structural only (foundation 5): this never inspects or judges the researcher's
    prose, only where one heading ends and the next begins.
    """
    sections: dict[str, str] = {}
    heading: str | None = None
    content: list[str] = []
    for line in body.splitlines():
        if line.startswith("## "):
            if heading is not None:
                sections[heading] = "\n".join(content).strip()
            heading = line[3:].strip().lower()
            content = []
        elif heading is not None:
            content.append(line)
    if heading is not None:
        sections[heading] = "\n".join(content).strip()
    return sections


def _status_bullets(text: str) -> tuple[str, ...]:
    items = []
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("-"):
            stripped = stripped[1:].strip()
        if stripped:
            items.append(stripped)
    return tuple(items)


@dataclass(frozen=True)
class _Unit:
    """A parsed (or unparseable) unit folder under experiments/, for internal reuse."""

    path: Path
    rel: str
    error: str | None
    fields: dict[str, Any]
    kind: UnitKind | None
    status: str | None


def run_checks(project_root: Path) -> CheckReport:
    """Run every WP2 rule against the project at ``project_root``. Read-only."""
    units = _load_units(project_root)

    findings: list[Finding] = []
    findings += _check_frontmatter_schema(units)
    findings += _check_evidence_pointers(units)
    findings += _check_receipt_completeness(units)

    suggestions: list[Suggestion] = []
    if _is_git_repo(project_root):
        findings += _check_log_immutability(project_root, units)
    else:
        suggestions.append(
            Suggestion(
                SUGGEST_GIT_UNAVAILABLE,
                ".",
                "not a Git repository: raw-log immutability under logs/ cannot be verified.",
            )
        )

    findings += _check_status_drift(project_root, units)
    findings += _check_structure_drift(project_root, units)
    findings += _check_closed_question_completeness(units)

    suggestions += _suggest_hpc(project_root, units)
    suggestions += _suggest_grouping(units)
    suggestions += _suggest_paper_overlay(project_root)

    return CheckReport(findings=tuple(findings), suggestions=tuple(suggestions))


# --- loading -----------------------------------------------------------------


def _load_units(project_root: Path) -> list[_Unit]:
    experiments_dir = project_root / "experiments"
    if not experiments_dir.is_dir():
        return []

    units: list[_Unit] = []
    for entry in sorted(experiments_dir.iterdir(), key=lambda item: item.name):
        readme = entry / "README.md"
        if not entry.is_dir() or not readme.is_file():
            continue
        rel = str(entry.relative_to(project_root))
        try:
            fields, _body = frontmatter.read(readme)
        except frontmatter.FrontmatterError as error:
            units.append(
                _Unit(path=entry, rel=rel, error=str(error), fields={}, kind=None, status=None)
            )
            continue

        kind: UnitKind | None
        try:
            kind = UnitKind(fields.get("kind"))
        except ValueError:
            kind = None
        status = fields.get("status")
        units.append(
            _Unit(
                path=entry,
                rel=rel,
                error=None,
                fields=fields,
                kind=kind,
                status=str(status) if status is not None else None,
            )
        )
    return units


# --- rule 1: frontmatter schema ----------------------------------------------


def _check_frontmatter_schema(units: list[_Unit]) -> list[Finding]:
    findings: list[Finding] = []
    for unit in units:
        readme_rel = f"{unit.rel}/README.md"
        if unit.error is not None:
            findings.append(
                Finding(
                    RULE_FRONTMATTER,
                    ERROR,
                    readme_rel,
                    f"frontmatter block is missing or malformed: {unit.error}",
                )
            )
            continue
        if unit.kind is None:
            findings.append(
                Finding(
                    RULE_FRONTMATTER,
                    ERROR,
                    readme_rel,
                    f"kind {unit.fields.get('kind')!r} is not a recognized unit kind",
                )
            )
            continue
        allowed = units_module.allowed_statuses(unit.kind)
        if unit.status not in allowed:
            findings.append(
                Finding(
                    RULE_FRONTMATTER,
                    ERROR,
                    readme_rel,
                    f"status {unit.status!r} is not legal for kind "
                    f"'{unit.kind.value}' (expected one of {list(allowed)})",
                )
            )
        for field in units_module.required_fields(unit.kind):
            if field not in unit.fields:
                findings.append(
                    Finding(
                        RULE_FRONTMATTER, ERROR, readme_rel, f"missing required field '{field}'"
                    )
                )
    return findings


# --- rule 2: evidence pointers resolve ---------------------------------------


def _as_targets(value: Any) -> list[str]:
    if isinstance(value, str):
        stripped = value.strip()
        return [stripped] if stripped else []
    if isinstance(value, list):
        return [str(item).strip() for item in value if str(item).strip()]
    return []


def _is_closed(kind: UnitKind, status: str | None) -> bool:
    if kind is UnitKind.stage:
        return status in _CLOSED_STAGE_STATUSES
    return status in _CLOSED_QUESTION_STATUSES


def _pointer_resolves(unit_path: Path, field: str, target: str, closed: bool) -> bool:
    candidate = unit_path / target
    if candidate.exists():
        return True
    if field == "log" and not closed:
        # `smairt unit new question` pre-fills log: with the filename the probe
        # is expected to write. For an open/active unit that hasn't run yet,
        # the containing logs/ folder existing is enough to call it resolved.
        return candidate.parent.is_dir()
    return False


def _check_evidence_pointers(units: list[_Unit]) -> list[Finding]:
    findings: list[Finding] = []
    for unit in units:
        if unit.kind is None:
            continue
        readme_rel = f"{unit.rel}/README.md"
        closed = _is_closed(unit.kind, unit.status)
        for field in _POINTER_FIELDS:
            if field not in unit.fields:
                continue
            targets = _as_targets(unit.fields[field])
            if not targets:
                if closed and field in ("script", "log"):
                    findings.append(
                        Finding(
                            RULE_EVIDENCE_POINTERS,
                            ERROR,
                            readme_rel,
                            f"closed unit's '{field}:' is empty",
                        )
                    )
                continue
            for target in targets:
                if not _pointer_resolves(unit.path, field, target, closed):
                    findings.append(
                        Finding(
                            RULE_EVIDENCE_POINTERS,
                            ERROR,
                            readme_rel,
                            f"'{field}: {target}' does not resolve to an existing path",
                        )
                    )
    return findings


# --- rule 3: receipt completeness --------------------------------------------


def _check_receipt_completeness(units: list[_Unit]) -> list[Finding]:
    findings: list[Finding] = []
    for unit in units:
        if unit.kind is None:
            continue
        tool = unit.fields.get("tool")
        if not tool:
            continue
        readme_rel = f"{unit.rel}/README.md"
        if not str(unit.fields.get("tool_version", "")).strip():
            findings.append(
                Finding(
                    RULE_RECEIPT_COMPLETENESS,
                    ERROR,
                    readme_rel,
                    "receipt unit ('tool:' set) has an empty 'tool_version:'",
                )
            )
        if not str(unit.fields.get("command", "")).strip():
            findings.append(
                Finding(
                    RULE_RECEIPT_COMPLETENESS,
                    ERROR,
                    readme_rel,
                    "receipt unit ('tool:' set) has an empty 'command:'",
                )
            )
        targets = _as_targets(unit.fields.get("log"))
        if not targets:
            findings.append(
                Finding(
                    RULE_RECEIPT_COMPLETENESS,
                    ERROR,
                    readme_rel,
                    "receipt unit ('tool:' set) has no 'log:' pointer",
                )
            )
        else:
            missing = [target for target in targets if not (unit.path / target).exists()]
            if missing:
                findings.append(
                    Finding(
                        RULE_RECEIPT_COMPLETENESS,
                        ERROR,
                        readme_rel,
                        f"receipt unit's log does not exist: {', '.join(missing)}",
                    )
                )
    return findings


# --- rule 4: raw-log immutability --------------------------------------------


def _is_git_repo(project_root: Path) -> bool:
    if shutil.which("git") is None:
        return False
    result = subprocess.run(
        ["git", "rev-parse", "--is-inside-work-tree"],
        cwd=project_root,
        capture_output=True,
        text=True,
        check=False,
    )
    return result.returncode == 0 and result.stdout.strip() == "true"


def _git_modified_paths(project_root: Path, rel_dir: Path) -> set[str]:
    """Paths under ``rel_dir`` that changed after the commit that first added them.

    Two sources, unioned: commits where the file already existed and was
    modified (``--diff-filter=M`` excludes the add itself), and any working-tree
    or staged edit to an already-committed file that hasn't been committed yet
    (``git diff HEAD``) — the immutability violation someone is most likely to
    still be looking at when `smairt check` runs.
    """
    modified: set[str] = set()

    history = subprocess.run(
        ["git", "log", "--diff-filter=M", "--name-only", "--pretty=format:", "--", str(rel_dir)],
        cwd=project_root,
        capture_output=True,
        text=True,
        check=False,
    )
    if history.returncode == 0:
        modified.update(line.strip() for line in history.stdout.splitlines() if line.strip())

    working_tree = subprocess.run(
        ["git", "diff", "--name-only", "HEAD", "--", str(rel_dir)],
        cwd=project_root,
        capture_output=True,
        text=True,
        check=False,
    )
    if working_tree.returncode == 0:
        modified.update(line.strip() for line in working_tree.stdout.splitlines() if line.strip())

    return modified


def _check_log_immutability(project_root: Path, units: list[_Unit]) -> list[Finding]:
    findings: list[Finding] = []
    for unit in units:
        logs_dir = unit.path / "logs"
        if not logs_dir.is_dir():
            continue
        rel_logs = logs_dir.relative_to(project_root)
        for rel_path in sorted(_git_modified_paths(project_root, rel_logs)):
            absolute = project_root / rel_path
            if absolute.is_file() and absolute.name != ".gitkeep":
                findings.append(
                    Finding(
                        RULE_LOG_IMMUTABILITY,
                        ERROR,
                        rel_path,
                        "log file was modified after being committed; raw evidence must be immutable",
                    )
                )
    return findings


# --- rule 5: STATUS drift ----------------------------------------------------


def _coerce_date(value: object) -> date | None:
    if isinstance(value, datetime):
        return value.date()
    if isinstance(value, date):
        return value
    if isinstance(value, str):
        try:
            return date.fromisoformat(value)
        except ValueError:
            return None
    return None


def _newest_mtime_date(unit_dir: Path) -> date:
    newest: float | None = None
    for path in unit_dir.rglob("*"):
        if not path.is_file() or path.name == ".gitkeep":
            continue
        mtime = path.stat().st_mtime
        if newest is None or mtime > newest:
            newest = mtime
    if newest is None:
        newest = unit_dir.stat().st_mtime
    return datetime.fromtimestamp(newest).date()


def _check_status_drift(project_root: Path, units: list[_Unit]) -> list[Finding]:
    status = read_status(project_root)
    if status is None or status.updated is None:
        return []

    findings: list[Finding] = []
    for unit in units:
        newest = _newest_mtime_date(unit.path)
        if newest > status.updated:
            findings.append(
                Finding(
                    RULE_STATUS_DRIFT,
                    WARNING,
                    unit.rel,
                    f"changed {newest.isoformat()}, after STATUS.md was last updated "
                    f"{status.updated.isoformat()}",
                )
            )
    return findings


# --- rule 6: structure drift --------------------------------------------------


def _check_structure_drift(project_root: Path, units: list[_Unit]) -> list[Finding]:
    findings: list[Finding] = []
    experiments_dir = project_root / "experiments"
    if experiments_dir.is_dir():
        for entry in sorted(experiments_dir.iterdir(), key=lambda item: item.name):
            if entry.is_dir():
                continue
            if entry.name == "README.md":
                continue
            findings.append(
                Finding(
                    RULE_STRUCTURE_DRIFT,
                    WARNING,
                    f"experiments/{entry.name}",
                    "file is loose directly under experiments/, outside any unit folder",
                )
            )
    if project_root.is_dir():
        for entry in sorted(project_root.iterdir(), key=lambda item: item.name):
            if not entry.is_dir() or entry.name.startswith("."):
                continue
            if entry.name in _KNOWN_TOP_LEVEL_DIRS:
                continue
            findings.append(
                Finding(
                    RULE_STRUCTURE_DRIFT,
                    WARNING,
                    entry.name,
                    "top-level folder is not part of the known scaffold "
                    "(background/, data/, scripts/, experiments/, results/, hpc/)",
                )
            )
    return findings


# --- rule 7: closed-question completeness ------------------------------------


def _check_closed_question_completeness(units: list[_Unit]) -> list[Finding]:
    findings: list[Finding] = []
    for unit in units:
        if unit.kind is not UnitKind.question:
            continue
        if unit.status not in _CLOSED_QUESTION_STATUSES:
            continue
        verdict = str(unit.fields.get("verdict", "")).strip()
        if not verdict:
            findings.append(
                Finding(
                    RULE_CLOSED_QUESTION,
                    ERROR,
                    f"{unit.rel}/README.md",
                    f"status '{unit.status}' requires a non-empty verdict",
                )
            )
    return findings


# --- rule 8: growth suggestions (advisory channel) ---------------------------


def _contains_slurm_content(unit_dir: Path) -> bool:
    for path in unit_dir.rglob("*"):
        if not path.is_file() or path.name == ".gitkeep":
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        if "sbatch" in text.lower():
            return True
    return False


def _suggest_hpc(project_root: Path, units: list[_Unit]) -> list[Suggestion]:
    if (project_root / "hpc").is_dir():
        return []
    for unit in units:
        if _contains_slurm_content(unit.path):
            return [
                Suggestion(
                    SUGGEST_HPC,
                    unit.rel,
                    "contains SLURM/sbatch content but this project has no hpc/ folder; "
                    "consider adding one to hold submission templates.",
                )
            ]
    return []


def _question_slug_word(unit: _Unit) -> str | None:
    name = unit.path.name
    if "_" not in name:
        return None
    _prefix, slug = name.split("_", 1)
    if not slug:
        return None
    return slug.split("-", 1)[0]


def _suggest_grouping(units: list[_Unit]) -> list[Suggestion]:
    groups: dict[str, list[str]] = {}
    for unit in units:
        if unit.kind is not UnitKind.question:
            continue
        word = _question_slug_word(unit)
        if not word:
            continue
        groups.setdefault(word, []).append(unit.rel)

    suggestions: list[Suggestion] = []
    for word, paths in sorted(groups.items()):
        if len(paths) >= 3:
            suggestions.append(
                Suggestion(
                    SUGGEST_GROUPING,
                    paths[0],
                    f"{len(paths)} question units share the leading word '{word}' "
                    f"({', '.join(paths)}); a grouping subfolder under experiments/ may be earned.",
                )
            )
    return suggestions


def _suggest_paper_overlay(project_root: Path) -> list[Suggestion]:
    status_path = project_root / "STATUS.md"
    if not status_path.is_file():
        return []
    text = status_path.read_text(encoding="utf-8", errors="ignore").lower()
    if any(word in text for word in _PAPER_WORDS):
        return [
            Suggestion(
                SUGGEST_PAPER_OVERLAY,
                "STATUS.md",
                "mentions paper/manuscript/figure-legend work; the Paper overlay is a "
                "deferred future capability, not yet supported.",
            )
        ]
    return []


# --- output rendering ---------------------------------------------------------


def render_human(report: CheckReport) -> str:
    """Render findings grouped by severity, then suggestions, then a summary line."""
    errors = [finding for finding in report.findings if finding.severity == ERROR]
    warnings = [finding for finding in report.findings if finding.severity == WARNING]

    lines: list[str] = []
    if errors:
        lines.append("Errors:")
        lines.extend(f"  {finding.id} {finding.path}: {finding.message}" for finding in errors)
    if warnings:
        lines.append("Warnings:")
        lines.extend(f"  {finding.id} {finding.path}: {finding.message}" for finding in warnings)
    if not report.findings:
        lines.append("No errors or warnings.")

    if report.suggestions:
        lines.append("")
        lines.append("Suggestions:")
        lines.extend(
            f"  {suggestion.id} {suggestion.path}: {suggestion.message}"
            for suggestion in report.suggestions
        )

    lines.append("")
    lines.append(
        f"{len(errors)} error(s), {len(warnings)} warning(s), "
        f"{len(report.suggestions)} suggestion(s)."
    )
    return "\n".join(lines)


def to_json(report: CheckReport) -> dict[str, Any]:
    """Render ``report`` as the ``--json`` payload: findings, suggestions, summary."""
    errors = sum(1 for finding in report.findings if finding.severity == ERROR)
    warnings = sum(1 for finding in report.findings if finding.severity == WARNING)
    return {
        "findings": [asdict(finding) for finding in report.findings],
        "suggestions": [asdict(suggestion) for suggestion in report.suggestions],
        "summary": {
            "errors": errors,
            "warnings": warnings,
            "suggestions": len(report.suggestions),
            "exit_code": report.exit_code,
        },
    }
