"""``smairt check`` — the state contract (WP2).

Tier-2 enforcement (spec Part I, foundation 2): what tooling cannot generate at
creation time (tier 1), it verifies mechanically here. Derived-first (foundation
3): this module reads frontmatter, the filesystem, and Git; it never maintains a
database of its own, and it never writes anything — the one deliberate exception
elsewhere in the codebase, ``results/INDEX.md``, is regenerated by
:mod:`smairt.index`, not here.

Public entry point: :func:`run_checks`, returning a :class:`CheckReport`.

:func:`read_status` is the single reader of ``STATUS.md`` (frontmatter *and* its
``## Heading`` body sections) — reused by rule 5 below and by ``smairt status`` (WP3).

Finding IDs
-----------
Every rule below carries exactly one stable ID (the *rule* is the unit of
identity, not each way it can be violated — a rule's ``message`` text carries
the specifics). IDs are referenced by tests and, later, by WP4's hooks, so they
must not be renumbered once shipped.

Findings (severity error/warning; each instance affects the process exit code)::

    SMAIRT001  Frontmatter schema invalid: block missing/malformed, kind not
               recognized, status illegal for that kind, or a required field
               (per smairt.units) absent.                              [error]
    SMAIRT002  An evidence pointer (script:/log:/outputs:/paths:) does not
               resolve, or a CLOSED unit's script:/log: is empty.       [error]
    SMAIRT003  Receipt completeness: a unit with tool: set has an empty
               tool_version:, empty command:, or a log: that does not exist.
                                                                          [error]
    SMAIRT004  Raw-log immutability: a file under a unit's logs/ was modified
               in a later commit than the one that added it.            [error]
    SMAIRT005  STATUS drift: STATUS.md's updated: is older than a unit that
               has changed since.                                     [warning]
    SMAIRT006  Structure drift: a file loose directly under experiments/
               (outside any unit folder), or an unrecognized top-level
               project folder.                                        [warning]
    SMAIRT007  Closed-question completeness: status in {supported, refuted,
               inconclusive, dead-end} with an empty verdict:.          [error]

Advisory suggestions (a separate channel; never affect the exit code)::

    SMAIRT101  Git is unavailable, so raw-log immutability (rule SMAIRT004)
               could not be checked at all — one note, not per-file.
    SMAIRT102  SLURM/sbatch content found in a unit but the project has no
               hpc/ folder yet.
    SMAIRT103  Three or more question units share a leading slug word: a
               grouping subfolder may be earned.
    SMAIRT104  STATUS.md mentions paper/manuscript/figure-legend work: a
               pointer to the (deferred) Paper overlay.
    SMAIRT105  A data/<x>/ subfolder exists with no README, or a README with
               no locations: entry recorded -- one note, not per-dataset.

Judgment calls a reviewer should know about
--------------------------------------------
* ``smairt unit new question`` pre-fills ``log:`` with the filename the probe
  is expected to write (``logs/<slug>.log``) before it has run. Rule SMAIRT002
  treats that as resolved for an OPEN/ACTIVE unit as long as the containing
  ``logs/`` folder exists — only a CLOSED unit is held to the exact file
  existing. This is what lets a freshly created, not-yet-run question pass
  check with zero findings (WP1's own acceptance criterion).
* Rule SMAIRT004 (log immutability) is skipped, in favor of the single
  SMAIRT101 advisory, whenever the project is not inside a Git work tree —
  this keeps `smairt check` usable before a researcher runs ``git init``.
* Rule SMAIRT005 (STATUS drift) compares calendar dates only (a file's mtime
  truncated to a date vs. STATUS.md's ``updated:`` date), not timestamps —
  matching the day-granularity the frontmatter schemas already use.
* Rule 8's growth suggestions each fire at most once per run (naming the
  first offending unit, not every one) — they are prompts to notice a
  pattern, not a per-file audit. SMAIRT105 (dataset locations) follows the
  same convention, naming the first data/<x>/ subfolder missing a recorded
  location rather than every one — a project can accumulate many datasets,
  and one nudge is enough to send a researcher to `smairt data list` to see
  the rest, rather than flooding `smairt check`'s output per dataset.
* Rule SMAIRT002's ``paths:`` field (case 3, spec Part II: reference units)
  resolves relative to the PROJECT ROOT, not the unit folder — it names
  pre-existing paths elsewhere in the tree. Every other pointer field
  (``script:``/``log:``/``outputs:``) stays unit-relative, as before.
* Rule SMAIRT006 (structure drift) also recognizes ``smairt.yaml``'s
  ``adoption.known_folders`` (written by ``smairt adopt``) as legitimate
  top-level folders, on top of the fixed scaffold set — an adopted project's
  pre-existing directories don't warn; anything new appearing after adoption
  still does.
"""

from __future__ import annotations

import subprocess
from dataclasses import asdict, dataclass
from datetime import date, datetime
from pathlib import Path
from typing import Any

import yaml

from smairt import frontmatter
from smairt import units as units_module
from smairt.project import is_git_work_tree
from smairt.units import UnitKind

ERROR = "error"
WARNING = "warning"

RULE_FRONTMATTER = "SMAIRT001"
RULE_EVIDENCE_POINTERS = "SMAIRT002"
RULE_RECEIPT_COMPLETENESS = "SMAIRT003"
RULE_LOG_IMMUTABILITY = "SMAIRT004"
RULE_STATUS_DRIFT = "SMAIRT005"
RULE_STRUCTURE_DRIFT = "SMAIRT006"
RULE_CLOSED_QUESTION = "SMAIRT007"

SUGGEST_GIT_UNAVAILABLE = "SMAIRT101"
SUGGEST_HPC = "SMAIRT102"
SUGGEST_GROUPING = "SMAIRT103"
SUGGEST_PAPER_OVERLAY = "SMAIRT104"
SUGGEST_DATASET_LOCATIONS = "SMAIRT105"

_POINTER_FIELDS = ("script", "log", "outputs", "paths")
_KNOWN_TOP_LEVEL_DIRS = frozenset(
    {"background", "data", "scripts", "experiments", "results", "hpc"}
)
_CLOSED_STAGE_STATUSES = frozenset({"frozen", "dead-end"})
_CLOSED_QUESTION_STATUSES = frozenset({"supported", "refuted", "inconclusive", "dead-end"})
_PAPER_WORDS = ("paper", "manuscript", "figure legend")


@dataclass(frozen=True)
class Finding:
    """One violation of the state contract. ``severity`` is ``error`` or ``warning``."""

    id: str
    severity: str
    path: str
    message: str


@dataclass(frozen=True)
class Suggestion:
    """One growth-channel note. Advisory only: never affects the exit code."""

    id: str
    path: str
    message: str


@dataclass(frozen=True)
class CheckReport:
    """The full result of :func:`run_checks`."""

    findings: tuple[Finding, ...]
    suggestions: tuple[Suggestion, ...]

    @property
    def exit_code(self) -> int:
        """1 if there are any errors/warnings, else 0 — what the CLI process exits with.

        Suggestions never affect this: they're advisory-only, so a project
        with suggestions but zero findings still exits 0 (success).
        """
        return 1 if self.findings else 0


@dataclass(frozen=True)
class StatusDocument:
    """The parsed contents of STATUS.md — the project's one hand-maintained ledger
    (Part I, foundation 3). This is the single reader for STATUS.md: :func:`run_checks`
    consults only ``updated`` (rule 5, STATUS drift); ``smairt status`` (WP3) reads the
    rest to print Focus/Next/Open questions. Keeping both behind :func:`read_status`
    means there is exactly one place that parses this file.
    """

    updated: date | None
    focus: str
    next_step: str
    open_questions: tuple[str, ...]
    decisions: tuple[str, ...]


def read_status(project_root: Path) -> StatusDocument | None:
    """Read and parse ``STATUS.md``, or ``None`` if it is absent or malformed."""
    status_path = project_root / "STATUS.md"
    if not status_path.is_file():
        return None
    try:
        fields, body = frontmatter.read(status_path)
    except frontmatter.FrontmatterError:
        return None
    sections = _split_status_sections(body)
    return StatusDocument(
        updated=_coerce_date(fields.get("updated")),
        focus=sections.get("focus", ""),
        next_step=sections.get("next", ""),
        open_questions=_status_bullets(sections.get("open questions", "")),
        decisions=_status_bullets(sections.get("decisions", "")),
    )


def _split_status_sections(body: str) -> dict[str, str]:
    """Split a STATUS.md body into ``## Heading`` sections, keyed by lowercase heading.

    Structural only (foundation 5): this never inspects or judges the researcher's
    prose, only where one heading ends and the next begins.
    """
    sections: dict[str, str] = {}
    heading: str | None = None
    content: list[str] = []
    for line in body.splitlines():
        if line.startswith("## "):
            if heading is not None:
                sections[heading] = "\n".join(content).strip()
            heading = line[3:].strip().lower()
            content = []
        elif heading is not None:
            content.append(line)
    if heading is not None:
        sections[heading] = "\n".join(content).strip()
    return sections


def _status_bullets(text: str) -> tuple[str, ...]:
    """Pull the ``- item`` bullet lines out of one STATUS.md section's text.

    Used for the "Open questions" and "Decisions" sections, which are
    written as a Markdown bullet list. Non-bullet lines are dropped rather
    than raising, since this is reading free-text prose (foundation 5: never
    judge the researcher's prose) — a section that isn't a tidy bullet list
    just yields fewer (or zero) items instead of erroring.
    """
    items = []
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("-"):
            stripped = stripped[1:].strip()
        if stripped:
            items.append(stripped)
    return tuple(items)


@dataclass(frozen=True)
class _Unit:
    """A parsed (or unparseable) unit folder under experiments/, for internal reuse."""

    path: Path
    rel: str
    error: str | None
    fields: dict[str, Any]
    kind: UnitKind | None
    status: str | None


def run_checks(project_root: Path) -> CheckReport:
    """Run every WP2 rule against the project at ``project_root``. Read-only.

    This is the one function that ties all eight rules together: it loads
    every unit once (:func:`_load_units`), then hands that same list to each
    rule function in turn, collecting their findings/suggestions into one
    report. To add a new rule, write a ``_check_*`` (findings) or
    ``_suggest_*`` (suggestions) function following the pattern below and
    call it from here — see docs/ARCHITECTURE.md.
    """
    units = _load_units(project_root)

    findings: list[Finding] = []
    findings += _check_frontmatter_schema(units)
    findings += _check_evidence_pointers(project_root, units)
    findings += _check_receipt_completeness(units)

    suggestions: list[Suggestion] = []
    if is_git_work_tree(project_root):
        findings += _check_log_immutability(project_root, units)
    else:
        # No Git, no history to check for edits after the fact -- rule
        # SMAIRT004 simply can't run, so we say so once (SMAIRT101) instead
        # of silently skipping it.
        suggestions.append(
            Suggestion(
                SUGGEST_GIT_UNAVAILABLE,
                ".",
                "not a Git repository: raw-log immutability under logs/ cannot be verified.",
            )
        )

    findings += _check_status_drift(project_root, units)
    findings += _check_structure_drift(project_root, units)
    findings += _check_closed_question_completeness(units)

    suggestions += _suggest_hpc(project_root, units)
    suggestions += _suggest_grouping(units)
    suggestions += _suggest_paper_overlay(project_root)
    suggestions += _suggest_dataset_locations(project_root)

    return CheckReport(findings=tuple(findings), suggestions=tuple(suggestions))


# --- loading -----------------------------------------------------------------


def _load_units(project_root: Path) -> list[_Unit]:
    """Read every unit folder under ``experiments/`` into a list of :class:`_Unit`.

    This is the single place every rule below gets its unit data from, so
    each rule function only has to loop over an already-parsed list instead
    of re-reading the filesystem itself. A unit whose README fails to parse
    still becomes a ``_Unit`` (with ``error`` set and ``kind``/``status`` left
    ``None``) rather than being skipped — that's what lets rule 1
    (frontmatter schema) report it as a SMAIRT001 finding.
    """
    experiments_dir = project_root / "experiments"
    if not experiments_dir.is_dir():
        return []

    units: list[_Unit] = []
    for entry in sorted(experiments_dir.iterdir(), key=lambda item: item.name):
        readme = entry / "README.md"
        if not entry.is_dir() or not readme.is_file():
            continue
        rel = str(entry.relative_to(project_root))
        try:
            fields, _body = frontmatter.read(readme)
        except frontmatter.FrontmatterError as error:
            units.append(
                _Unit(path=entry, rel=rel, error=str(error), fields={}, kind=None, status=None)
            )
            continue

        kind: UnitKind | None
        try:
            kind = UnitKind(fields.get("kind"))
        except ValueError:
            kind = None
        status = fields.get("status")
        units.append(
            _Unit(
                path=entry,
                rel=rel,
                error=None,
                fields=fields,
                kind=kind,
                status=str(status) if status is not None else None,
            )
        )
    return units


# --- rule 1: frontmatter schema ----------------------------------------------


def _check_frontmatter_schema(units: list[_Unit]) -> list[Finding]:
    """Rule SMAIRT001: every unit's frontmatter must parse and match its schema.

    Checked in order, each guarded by ``continue`` so a badly broken unit
    doesn't also get flooded with follow-on findings that wouldn't make
    sense: (1) does the frontmatter parse at all (caught earlier, by
    :func:`_load_units`); (2) is ``kind:`` a recognized value (``stage`` or
    ``question``). Once both of those pass, (3) ``status:`` and (4) every
    required field (from :mod:`smairt.units`) are checked independently, so
    a unit can rack up several findings at once for those two.
    """
    findings: list[Finding] = []
    for unit in units:
        readme_rel = f"{unit.rel}/README.md"

        # Every finding in this rule shares the same id and severity; only the
        # message changes, so a tiny local helper keeps each check below to
        # one line instead of a five-line Finding(...) call.
        def flag(message: str) -> None:
            findings.append(Finding(RULE_FRONTMATTER, ERROR, readme_rel, message))

        if unit.error is not None:
            flag(f"frontmatter block is missing or malformed: {unit.error}")
            continue
        if unit.kind is None:
            flag(f"kind {unit.fields.get('kind')!r} is not a recognized unit kind")
            continue
        allowed = units_module.allowed_statuses(unit.kind)
        if unit.status not in allowed:
            flag(
                f"status {unit.status!r} is not legal for kind "
                f"'{unit.kind.value}' (expected one of {list(allowed)})"
            )
        for field in units_module.required_fields(unit.kind):
            if field not in unit.fields:
                flag(f"missing required field '{field}'")
    return findings


# --- rule 2: evidence pointers resolve ---------------------------------------


def _as_targets(value: Any) -> list[str]:
    """Normalize a frontmatter pointer field into a list of path strings.

    A pointer field (``script:``, ``log:``, ``outputs:``, ``paths:``) can be
    written as a single string or as a YAML list — this treats both the same
    way, dropping blanks so an empty ``log: ""`` becomes an empty list rather
    than a list containing one blank string.
    """
    if isinstance(value, str):
        stripped = value.strip()
        return [stripped] if stripped else []
    if isinstance(value, list):
        return [str(item).strip() for item in value if str(item).strip()]
    return []


def _is_closed(kind: UnitKind, status: str | None) -> bool:
    """Is this unit "done" — no longer expected to change?

    A closed unit is held to a stricter standard (rule SMAIRT002: its
    script:/log: pointers must actually exist, not just be plausible).
    "Closed" means a different set of statuses for each kind: a stage is
    closed when frozen or dead-end; a question is closed by any status other
    than open (supported/refuted/inconclusive/dead-end).
    """
    if kind is UnitKind.stage:
        return status in _CLOSED_STAGE_STATUSES
    return status in _CLOSED_QUESTION_STATUSES


def _pointer_resolves(
    unit_path: Path, project_root: Path, field: str, target: str, closed: bool
) -> bool:
    """Does this one pointer field's target actually exist on disk?

    Example: ``script: analysis.py`` resolves if ``analysis.py`` exists next
    to the unit's README. Returns ``False`` (a finding) if not — with one
    exception for not-yet-run questions, explained below.
    """
    # A reference unit's `paths:` (case 3, spec Part II) names pre-existing
    # paths relative to the PROJECT ROOT, not the unit folder — it points
    # elsewhere in the tree, unlike script:/log:/outputs: which are unit-local.
    base = project_root if field == "paths" else unit_path
    candidate = base / target
    if candidate.exists():
        return True
    if field == "log" and not closed:
        # `smairt unit new question` pre-fills log: with the filename the probe
        # is expected to write. For an open/active unit that hasn't run yet,
        # the containing logs/ folder existing is enough to call it resolved.
        return candidate.parent.is_dir()
    return False


def _check_evidence_pointers(project_root: Path, units: list[_Unit]) -> list[Finding]:
    """Rule SMAIRT002: every evidence pointer must point at something real.

    Walks each of the four pointer fields (``script:``, ``log:``,
    ``outputs:``, ``paths:``) on every unit. An empty pointer is only a
    problem if the unit is closed and the field is script:/log: (an open
    unit is allowed to not have run yet); a non-empty pointer that doesn't
    resolve to a real path is always a problem, via :func:`_pointer_resolves`.
    """
    findings: list[Finding] = []
    for unit in units:
        if unit.kind is None:
            continue
        readme_rel = f"{unit.rel}/README.md"

        def flag(message: str) -> None:
            findings.append(Finding(RULE_EVIDENCE_POINTERS, ERROR, readme_rel, message))

        closed = _is_closed(unit.kind, unit.status)
        for field in _POINTER_FIELDS:
            if field not in unit.fields:
                continue
            targets = _as_targets(unit.fields[field])
            if not targets:
                # An empty pointer only matters once the unit is closed --
                # see _is_closed's docstring for why "closed" differs by kind.
                if closed and field in ("script", "log"):
                    flag(f"closed unit's '{field}:' is empty")
                continue
            for target in targets:
                if not _pointer_resolves(unit.path, project_root, field, target, closed):
                    flag(f"'{field}: {target}' does not resolve to an existing path")
    return findings


# --- rule 3: receipt completeness --------------------------------------------


def _check_receipt_completeness(units: list[_Unit]) -> list[Finding]:
    """Rule SMAIRT003: a "receipt" unit (``tool:`` set) must record its receipt fully.

    A unit becomes a receipt the moment its frontmatter has a non-empty
    ``tool:`` field (see :func:`smairt.units.create_stage`'s ``receipt=``
    option). Once it is one, three things are required: a non-blank
    ``tool_version:``, a non-blank ``command:``, and a ``log:`` that both is
    set AND points at a file that exists — unlike rule SMAIRT002, a receipt's
    log is never given the "not run yet" pass, because pointing at an outside
    tool's output only makes sense once that output exists.
    """
    findings: list[Finding] = []
    for unit in units:
        if unit.kind is None:
            continue
        tool = unit.fields.get("tool")
        if not tool:
            continue
        readme_rel = f"{unit.rel}/README.md"

        def flag(message: str) -> None:
            findings.append(Finding(RULE_RECEIPT_COMPLETENESS, ERROR, readme_rel, message))

        if not str(unit.fields.get("tool_version", "")).strip():
            flag("receipt unit ('tool:' set) has an empty 'tool_version:'")
        if not str(unit.fields.get("command", "")).strip():
            flag("receipt unit ('tool:' set) has an empty 'command:'")
        targets = _as_targets(unit.fields.get("log"))
        if not targets:
            flag("receipt unit ('tool:' set) has no 'log:' pointer")
        else:
            missing = [target for target in targets if not (unit.path / target).exists()]
            if missing:
                flag(f"receipt unit's log does not exist: {', '.join(missing)}")
    return findings


# --- rule 4: raw-log immutability --------------------------------------------


def _git_modified_paths(project_root: Path, rel_dir: Path) -> set[str]:
    """Paths under ``rel_dir`` that changed after the commit that first added them.

    Two sources, unioned: commits where the file already existed and was
    modified (``--diff-filter=M`` excludes the add itself), and any working-tree
    or staged edit to an already-committed file that hasn't been committed yet
    (``git diff HEAD``) — the immutability violation someone is most likely to
    still be looking at when `smairt check` runs.
    """
    modified: set[str] = set()

    history = subprocess.run(
        ["git", "log", "--diff-filter=M", "--name-only", "--pretty=format:", "--", str(rel_dir)],
        cwd=project_root,
        capture_output=True,
        text=True,
        check=False,
    )
    if history.returncode == 0:
        modified.update(line.strip() for line in history.stdout.splitlines() if line.strip())

    working_tree = subprocess.run(
        ["git", "diff", "--name-only", "HEAD", "--", str(rel_dir)],
        cwd=project_root,
        capture_output=True,
        text=True,
        check=False,
    )
    if working_tree.returncode == 0:
        modified.update(line.strip() for line in working_tree.stdout.splitlines() if line.strip())

    return modified


def _check_log_immutability(project_root: Path, units: list[_Unit]) -> list[Finding]:
    """Rule SMAIRT004: a file under a unit's ``logs/`` must never be edited after it lands.

    Raw logs are the ground truth a unit's conclusions are checked against;
    editing one after the fact would let someone rewrite the evidence. This
    asks Git (via :func:`_git_modified_paths`) which log files have a
    modification recorded after their first commit, and flags every one
    found. Only runs when :func:`smairt.project.is_git_work_tree` says Git history
    is available.
    """
    findings: list[Finding] = []
    for unit in units:
        logs_dir = unit.path / "logs"
        if not logs_dir.is_dir():
            continue
        rel_logs = logs_dir.relative_to(project_root)
        for rel_path in sorted(_git_modified_paths(project_root, rel_logs)):
            absolute = project_root / rel_path
            if absolute.is_file() and absolute.name != ".gitkeep":
                findings.append(
                    Finding(
                        RULE_LOG_IMMUTABILITY,
                        ERROR,
                        rel_path,
                        "log file was modified after being committed; raw evidence must be immutable",
                    )
                )
    return findings


# --- rule 5: STATUS drift ----------------------------------------------------


def _coerce_date(value: object) -> date | None:
    """Best-effort conversion of a YAML-parsed value into a plain ``date``.

    PyYAML usually parses an unquoted ``2026-08-12`` into a real ``date`` (or
    ``datetime``) already, but a hand-edited or oddly quoted value could come
    through as a string, or as something else entirely. Returns ``None``
    (rather than raising) for anything that isn't a recognizable date, since
    a malformed ``updated:`` shouldn't crash the whole check run.
    """
    if isinstance(value, datetime):
        return value.date()
    if isinstance(value, date):
        return value
    if isinstance(value, str):
        try:
            return date.fromisoformat(value)
        except ValueError:
            return None
    return None


def _newest_mtime_date(unit_dir: Path) -> date:
    """The calendar date of the most recently modified file inside ``unit_dir``.

    Walks every file under the unit (skipping ``.gitkeep`` placeholders) and
    takes the latest modification time, truncated to a date — matching the
    day-granularity STATUS.md's ``updated:`` field already uses, so the two
    are comparable. Falls back to the unit folder's own mtime if it somehow
    has no files at all (e.g. a fresh reference unit).
    """
    newest: float | None = None
    for path in unit_dir.rglob("*"):
        if not path.is_file() or path.name == ".gitkeep":
            continue
        mtime = path.stat().st_mtime
        if newest is None or mtime > newest:
            newest = mtime
    if newest is None:
        newest = unit_dir.stat().st_mtime
    return datetime.fromtimestamp(newest).date()


def _check_status_drift(project_root: Path, units: list[_Unit]) -> list[Finding]:
    """Rule SMAIRT005 (warning): flag units changed after STATUS.md was last updated.

    STATUS.md is the project's hand-maintained "what's going on" summary; if
    a unit has newer files than STATUS.md's own ``updated:`` date, that
    summary is probably stale. Skipped entirely if STATUS.md is missing,
    malformed, or has no ``updated:`` date to compare against.
    """
    status = read_status(project_root)
    if status is None or status.updated is None:
        return []

    findings: list[Finding] = []
    for unit in units:
        newest = _newest_mtime_date(unit.path)
        if newest > status.updated:
            findings.append(
                Finding(
                    RULE_STATUS_DRIFT,
                    WARNING,
                    unit.rel,
                    f"changed {newest.isoformat()}, after STATUS.md was last updated "
                    f"{status.updated.isoformat()}",
                )
            )
    return findings


# --- rule 6: structure drift --------------------------------------------------


def _adoption_known_folders(project_root: Path) -> frozenset[str]:
    """Read ``smairt.yaml``'s ``adoption.known_folders`` (empty if absent/malformed).

    ``smairt adopt`` records the top-level directories that already existed at
    adoption time here (Part II case 3); rule 6 treats them as recognized so an
    adopted project passes `smairt check` clean immediately. Folders appearing
    AFTER adoption are not in this list and still warn as usual.
    """
    path = project_root / "smairt.yaml"
    if not path.is_file():
        return frozenset()
    try:
        config = yaml.safe_load(path.read_text(encoding="utf-8"))
    except yaml.YAMLError:
        return frozenset()
    if not isinstance(config, dict):
        return frozenset()
    adoption = config.get("adoption")
    if not isinstance(adoption, dict):
        return frozenset()
    folders = adoption.get("known_folders")
    if not isinstance(folders, list):
        return frozenset()
    return frozenset(str(item) for item in folders)


def _check_structure_drift(project_root: Path, units: list[_Unit]) -> list[Finding]:
    """Rule SMAIRT006 (warning): flag files/folders outside the expected project shape.

    Two separate checks, both warnings rather than errors (the project still
    works, it just doesn't match the documented shape): (1) any file sitting
    loose directly under ``experiments/`` instead of inside a unit folder;
    (2) any top-level folder that isn't one of the standard scaffold folders
    (background/data/scripts/experiments/results/hpc) or one this project's
    ``smairt adopt`` already recorded as pre-existing (see
    :func:`_adoption_known_folders`).
    """
    findings: list[Finding] = []
    experiments_dir = project_root / "experiments"
    if experiments_dir.is_dir():
        for entry in sorted(experiments_dir.iterdir(), key=lambda item: item.name):
            if entry.is_dir():
                continue
            if entry.name == "README.md":
                continue
            findings.append(
                Finding(
                    RULE_STRUCTURE_DRIFT,
                    WARNING,
                    f"experiments/{entry.name}",
                    "file is loose directly under experiments/, outside any unit folder",
                )
            )
    if project_root.is_dir():
        recognized = _KNOWN_TOP_LEVEL_DIRS | _adoption_known_folders(project_root)
        for entry in sorted(project_root.iterdir(), key=lambda item: item.name):
            if not entry.is_dir() or entry.name.startswith("."):
                continue
            if entry.name in recognized:
                continue
            findings.append(
                Finding(
                    RULE_STRUCTURE_DRIFT,
                    WARNING,
                    entry.name,
                    "top-level folder is not part of the known scaffold "
                    "(background/, data/, scripts/, experiments/, results/, hpc/) "
                    "or this adopted project's known_folders",
                )
            )
    return findings


# --- rule 7: closed-question completeness ------------------------------------


def _check_closed_question_completeness(units: list[_Unit]) -> list[Finding]:
    """Rule SMAIRT007: a closed question must record its verdict.

    "Closed" here means any question status other than open (supported,
    refuted, inconclusive, or dead-end) — the point of closing a question is
    to answer it, so a blank ``verdict:`` on a closed question means the
    answer was never actually written down.
    """
    findings: list[Finding] = []
    for unit in units:
        if unit.kind is not UnitKind.question:
            continue
        if unit.status not in _CLOSED_QUESTION_STATUSES:
            continue
        verdict = str(unit.fields.get("verdict", "")).strip()
        if not verdict:
            findings.append(
                Finding(
                    RULE_CLOSED_QUESTION,
                    ERROR,
                    f"{unit.rel}/README.md",
                    f"status '{unit.status}' requires a non-empty verdict",
                )
            )
    return findings


# --- rule 8: growth suggestions (advisory channel) ---------------------------


def _contains_slurm_content(unit_dir: Path) -> bool:
    """Does any file inside ``unit_dir`` mention ``sbatch`` (SLURM's submit command)?

    A crude but cheap text search, not a real SLURM script parser — good
    enough for the SMAIRT102 advisory, which is just a "you might want an
    hpc/ folder" nudge, not something a researcher needs to trust completely.
    """
    for path in unit_dir.rglob("*"):
        if not path.is_file() or path.name == ".gitkeep":
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        if "sbatch" in text.lower():
            return True
    return False


def _suggest_hpc(project_root: Path, units: list[_Unit]) -> list[Suggestion]:
    """Advisory SMAIRT102: nudge toward an ``hpc/`` folder if SLURM content shows up without one.

    Stops at the first unit with SLURM content (see :func:`_contains_slurm_content`)
    — this is a "notice the pattern" prompt, not an audit of every occurrence.
    """
    if (project_root / "hpc").is_dir():
        return []
    for unit in units:
        if _contains_slurm_content(unit.path):
            return [
                Suggestion(
                    SUGGEST_HPC,
                    unit.rel,
                    "contains SLURM/sbatch content but this project has no hpc/ folder; "
                    "consider adding one to hold submission templates.",
                )
            ]
    return []


def _question_slug_word(unit: _Unit) -> str | None:
    """The first word of a question unit's slug, for spotting a shared naming pattern.

    Example: folder ``2026-08-12_align-reads`` -> ``"align"``. A question
    folder is named ``date_slug``, and the slug's words are joined with
    ``-`` (see :mod:`smairt.text`), so splitting on ``_`` then ``-`` peels
    off exactly the leading word. Returns ``None`` if the name doesn't have
    the expected shape at all.
    """
    name = unit.path.name
    if "_" not in name:
        return None
    _prefix, slug = name.split("_", 1)
    if not slug:
        return None
    return slug.split("-", 1)[0]


def _suggest_grouping(units: list[_Unit]) -> list[Suggestion]:
    """Advisory SMAIRT103: nudge toward a grouping subfolder when 3+ questions share a leading word.

    Example: ``align-v1``, ``align-v2``, ``align-debug`` all start with
    "align" — three or more such questions might be a sign they'd read
    better grouped under a subfolder of experiments/. One suggestion per
    shared word, naming the first offending unit as the example.
    """
    groups: dict[str, list[str]] = {}
    for unit in units:
        if unit.kind is not UnitKind.question:
            continue
        word = _question_slug_word(unit)
        if not word:
            continue
        groups.setdefault(word, []).append(unit.rel)

    suggestions: list[Suggestion] = []
    for word, paths in sorted(groups.items()):
        if len(paths) >= 3:
            suggestions.append(
                Suggestion(
                    SUGGEST_GROUPING,
                    paths[0],
                    f"{len(paths)} question units share the leading word '{word}' "
                    f"({', '.join(paths)}); a grouping subfolder under experiments/ may be earned.",
                )
            )
    return suggestions


def _suggest_paper_overlay(project_root: Path) -> list[Suggestion]:
    """Advisory SMAIRT104: point at the (not-yet-built) Paper overlay if STATUS.md mentions paper work.

    A plain case-insensitive text search for "paper", "manuscript", or
    "figure legend" in STATUS.md — deliberately simple, since this is only a
    pointer to a deferred future feature, not a rule the researcher needs to
    satisfy.
    """
    status_path = project_root / "STATUS.md"
    if not status_path.is_file():
        return []
    text = status_path.read_text(encoding="utf-8", errors="ignore").lower()
    if any(word in text for word in _PAPER_WORDS):
        return [
            Suggestion(
                SUGGEST_PAPER_OVERLAY,
                "STATUS.md",
                "mentions paper/manuscript/figure-legend work; the Paper overlay is a "
                "deferred future capability, not yet supported.",
            )
        ]
    return []


def _dataset_missing_locations(dataset_dir: Path) -> bool:
    """Does this ``data/<x>/`` folder lack a usable ``locations:`` record?

    True when there is no ``README.md`` at all, the README has no
    frontmatter block, or its frontmatter has a ``locations:`` field that is
    missing, not a list, or an empty list — any of these means `smairt data
    list` would report zero locations for this dataset, i.e. nobody has
    written down where its bytes actually are.
    """
    readme = dataset_dir / "README.md"
    if not readme.is_file():
        return True
    try:
        fields, _body = frontmatter.read(readme)
    except frontmatter.FrontmatterError:
        return True
    locations = fields.get("locations")
    return not isinstance(locations, list) or not locations


def _suggest_dataset_locations(project_root: Path) -> list[Suggestion]:
    """Advisory SMAIRT105: nudge toward recording where a dataset's bytes live.

    Stops at the first ``data/<x>/`` subfolder with no usable ``locations:``
    record (see :func:`_dataset_missing_locations`) — like the rest of rule
    8, this is a "notice the pattern" prompt (point at `smairt data list` /
    `smairt data new` / `smairt data locate`), not a per-dataset audit; see
    the module docstring's "Judgment calls" section for why once-per-run was
    chosen over once-per-dataset.
    """
    data_dir = project_root / "data"
    if not data_dir.is_dir():
        return []
    for entry in sorted(data_dir.iterdir(), key=lambda item: item.name):
        if not entry.is_dir():
            continue
        if _dataset_missing_locations(entry):
            return [
                Suggestion(
                    SUGGEST_DATASET_LOCATIONS,
                    f"data/{entry.name}",
                    "has no recorded locations: entry; run `smairt data new` (if this "
                    "isn't a dataset yet) or `smairt data locate` to record where its "
                    "bytes actually live.",
                )
            ]
    return []


# --- output rendering ---------------------------------------------------------


def render_human(report: CheckReport) -> str:
    """Render findings grouped by severity, then suggestions, then a summary line."""
    errors = [finding for finding in report.findings if finding.severity == ERROR]
    warnings = [finding for finding in report.findings if finding.severity == WARNING]

    lines: list[str] = []
    if errors:
        lines.append("Errors:")
        lines.extend(f"  {finding.id} {finding.path}: {finding.message}" for finding in errors)
    if warnings:
        lines.append("Warnings:")
        lines.extend(f"  {finding.id} {finding.path}: {finding.message}" for finding in warnings)
    if not report.findings:
        lines.append("No errors or warnings.")

    if report.suggestions:
        lines.append("")
        lines.append("Suggestions:")
        lines.extend(
            f"  {suggestion.id} {suggestion.path}: {suggestion.message}"
            for suggestion in report.suggestions
        )

    lines.append("")
    lines.append(
        f"{len(errors)} error(s), {len(warnings)} warning(s), "
        f"{len(report.suggestions)} suggestion(s)."
    )
    return "\n".join(lines)


def to_json(report: CheckReport) -> dict[str, Any]:
    """Render ``report`` as the ``--json`` payload: findings, suggestions, summary."""
    errors = sum(1 for finding in report.findings if finding.severity == ERROR)
    warnings = sum(1 for finding in report.findings if finding.severity == WARNING)
    return {
        "findings": [asdict(finding) for finding in report.findings],
        "suggestions": [asdict(suggestion) for suggestion in report.suggestions],
        "summary": {
            "errors": errors,
            "warnings": warnings,
            "suggestions": len(report.suggestions),
            "exit_code": report.exit_code,
        },
    }
