"""``smairt index`` — regenerates ``results/INDEX.md``, the one-page evidence map.

Every unit under ``experiments/`` records its own status and points at its
own logs/figures. This module walks all of them and builds a single table
(one row per unit) so a researcher — or another tool — can see the whole
project's evidence at a glance without opening every unit's README.

INDEX.md is *derived*, not hand-written: it is always safe to regenerate,
and nothing in this file ever reads back what was there before. Called both
directly (``smairt index``) and as a side effect of ``smairt new``,
``smairt adopt``, and ``smairt status``.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from smairt import frontmatter

_HEADER = (
    "<!-- Generated by `smairt index`. Do not edit by hand. -->\n\n"
    "# Results index\n\n"
    "Every unit's evidence, in one map. Regenerate with `smairt index`.\n\n"
)
_TABLE_HEADER = (
    "| Unit | Kind | Status | Title | Logs | Figures |\n| --- | --- | --- | --- | --- | --- |\n"
)


@dataclass(frozen=True)
class UnitRecord:
    """One row of the results index: a unit and the evidence it points at."""

    path: str
    kind: str
    status: str
    title: str
    logs: tuple[str, ...]
    figures: tuple[str, ...]


def scan_units(project_root: Path) -> list[UnitRecord]:
    """Walk ``experiments/`` and read every unit's frontmatter header.

    Folder name order already reads top-down (numbered stages sort before dated
    questions), so no explicit re-sort is needed. Reusable by WP2/WP3 as well as
    ``smairt index``.
    """
    experiments_dir = project_root / "experiments"
    if not experiments_dir.is_dir():
        return []

    records = []
    for entry in sorted(experiments_dir.iterdir(), key=lambda item: item.name):
        readme = entry / "README.md"
        if not entry.is_dir() or not readme.is_file():
            continue
        fields, _ = frontmatter.read(readme)
        records.append(
            UnitRecord(
                path=f"experiments/{entry.name}",
                kind=str(fields.get("kind", "")),
                status=str(fields.get("status", "")),
                title=str(fields.get("title", "")),
                logs=_listed_files(entry / "logs"),
                figures=_listed_files(entry / "figures"),
            )
        )
    return records


def _listed_files(folder: Path) -> tuple[str, ...]:
    """List the file names directly inside ``folder``, alphabetically.

    Used for a unit's ``logs/`` and ``figures/`` subfolders. Skips
    ``.gitkeep`` (a placeholder Git needs to track an otherwise-empty
    folder — not real evidence) and returns an empty tuple if the folder
    doesn't exist yet (e.g. a question that hasn't produced figures).
    """
    if not folder.is_dir():
        return ()
    return tuple(
        sorted(item.name for item in folder.iterdir() if item.is_file() and item.name != ".gitkeep")
    )


def render_index(records: list[UnitRecord]) -> str:
    """Render ``results/INDEX.md`` content from scanned unit records."""
    rows = [
        "| [{path}]({path}/README.md) | {kind} | {status} | {title} | {logs} | {figures} |".format(
            path=record.path,
            kind=record.kind,
            status=record.status,
            title=record.title,
            logs=", ".join(record.logs) or "-",
            figures=", ".join(record.figures) or "-",
        )
        for record in records
    ]
    table_body = "\n".join(rows) + ("\n" if rows else "")
    return _HEADER + _TABLE_HEADER + table_body


def write_index(project_root: Path) -> Path:
    """Regenerate ``results/INDEX.md`` in place. This file is derived, not a skeleton.

    Unlike every other generated file, INDEX.md is meant to be overwritten on every
    call (Part I, foundation 3: derived-first state) — that is the point of it.
    """
    path = project_root / "results" / "INDEX.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_index(scan_units(project_root)), encoding="utf-8")
    return path
